slurmstepd: error: task/cgroup: unable to add task[pid=10766] to memory cg '(null)'
MANDATORY INPUT VARIABLES:
	NStates = 1
	NSteps = 1000
	dtI = 0.25 (fs)
	ESTEPS = 50
	ISTATE = 0
	FUNCTIONAL = WB97XD
	BASIS_SET = 6-311G
	CHARGE = 0
	MULTIPLICITY = 1
	MEMORY = 5 (GB)
	PARALLEL_FORCES = True
	NAMD_METHOD = EH
	EL_PROP = VV
	MD_ENSEMBLE = NVT
Input looks good.
Submitting electronic structure for step 0.
	Gaussian terminated normally in 17.06 s. (GS_NEW)
Submitting electronic structure for step 1.
	Gaussian terminated normally in 21.79 s. (GS_NEW)
Total QM took 21.94 s.
Submitting electronic structure for step 2.
	Gaussian terminated normally in 23.17 s. (GS_NEW)
Total QM took 24.19 s.
Submitting electronic structure for step 3.
	Gaussian terminated normally in 24.14 s. (GS_NEW)
Total QM took 25.59 s.
Submitting electronic structure for step 4.
	Gaussian terminated normally in 26.52 s. (GS_NEW)
Total QM took 27.94 s.
Submitting electronic structure for step 5.
	Gaussian terminated normally in 22.00 s. (GS_NEW)
Total QM took 22.26 s.
Submitting electronic structure for step 6.
	Gaussian terminated normally in 28.09 s. (GS_NEW)
Total QM took 28.71 s.
Submitting electronic structure for step 7.
	Gaussian terminated normally in 26.78 s. (GS_NEW)
Total QM took 27.52 s.
Submitting electronic structure for step 8.
	Gaussian terminated normally in 23.29 s. (GS_NEW)
Total QM took 23.40 s.
Submitting electronic structure for step 9.
	Gaussian terminated normally in 24.31 s. (GS_NEW)
Total QM took 24.42 s.
Submitting electronic structure for step 10.
	Gaussian terminated normally in 25.34 s. (GS_NEW)
Total QM took 25.45 s.
Submitting electronic structure for step 11.
	Gaussian terminated normally in 25.39 s. (GS_NEW)
Total QM took 25.51 s.
Submitting electronic structure for step 12.
	Gaussian terminated normally in 27.74 s. (GS_NEW)
Total QM took 27.85 s.
Submitting electronic structure for step 13.
	Gaussian terminated normally in 27.40 s. (GS_NEW)
Total QM took 27.52 s.
Submitting electronic structure for step 14.
	Gaussian terminated normally in 23.42 s. (GS_NEW)
Total QM took 24.16 s.
Submitting electronic structure for step 15.
	Gaussian terminated normally in 23.67 s. (GS_NEW)
Total QM took 23.79 s.
Submitting electronic structure for step 16.
	Gaussian terminated normally in 26.28 s. (GS_NEW)
Total QM took 26.39 s.
Submitting electronic structure for step 17.
	Gaussian terminated normally in 30.85 s. (GS_NEW)
Total QM took 30.96 s.
Submitting electronic structure for step 18.
	Gaussian terminated normally in 25.53 s. (GS_NEW)
Total QM took 25.65 s.
Submitting electronic structure for step 19.
	Gaussian terminated normally in 18.41 s. (GS_NEW)
Total QM took 18.83 s.
Submitting electronic structure for step 20.
	Gaussian terminated normally in 30.36 s. (GS_NEW)
Total QM took 30.47 s.
Submitting electronic structure for step 21.
	Gaussian terminated normally in 24.37 s. (GS_NEW)
Total QM took 25.38 s.
Submitting electronic structure for step 22.
	Gaussian terminated normally in 22.33 s. (GS_NEW)
Total QM took 22.44 s.
Submitting electronic structure for step 23.
	Gaussian terminated normally in 24.48 s. (GS_NEW)
Total QM took 24.59 s.
Submitting electronic structure for step 24.
	Gaussian terminated normally in 31.20 s. (GS_NEW)
Total QM took 31.32 s.
Submitting electronic structure for step 25.
	Gaussian terminated normally in 25.09 s. (GS_NEW)
Total QM took 25.20 s.
Submitting electronic structure for step 26.
	Gaussian terminated normally in 28.42 s. (GS_NEW)
Total QM took 28.91 s.
Submitting electronic structure for step 27.
	Gaussian terminated normally in 21.09 s. (GS_NEW)
Total QM took 21.34 s.
Submitting electronic structure for step 28.
	Gaussian terminated normally in 22.72 s. (GS_NEW)
Total QM took 22.85 s.
Submitting electronic structure for step 29.
	Gaussian terminated normally in 25.96 s. (GS_NEW)
Total QM took 26.31 s.
Submitting electronic structure for step 30.
	Gaussian terminated normally in 27.78 s. (GS_NEW)
Total QM took 30.58 s.
Submitting electronic structure for step 31.
	Gaussian terminated normally in 23.27 s. (GS_NEW)
Total QM took 23.51 s.
Submitting electronic structure for step 32.
	Gaussian terminated normally in 22.20 s. (GS_NEW)
Total QM took 22.48 s.
Submitting electronic structure for step 33.
	Gaussian terminated normally in 24.75 s. (GS_NEW)
Total QM took 25.00 s.
Submitting electronic structure for step 34.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 26.88 s.
Submitting electronic structure for step 35.
	Gaussian terminated normally in 25.68 s. (GS_NEW)
Total QM took 25.90 s.
Submitting electronic structure for step 36.
	Gaussian terminated normally in 20.04 s. (GS_NEW)
Total QM took 20.28 s.
Submitting electronic structure for step 37.
	Gaussian terminated normally in 23.25 s. (GS_NEW)
Total QM took 23.38 s.
Submitting electronic structure for step 38.
	Gaussian terminated normally in 25.82 s. (GS_NEW)
Total QM took 25.94 s.
Submitting electronic structure for step 39.
	Gaussian terminated normally in 27.26 s. (GS_NEW)
Total QM took 28.64 s.
Submitting electronic structure for step 40.
	Gaussian terminated normally in 32.27 s. (GS_NEW)
Total QM took 32.51 s.
Submitting electronic structure for step 41.
	Gaussian terminated normally in 25.54 s. (GS_NEW)
Total QM took 25.81 s.
Submitting electronic structure for step 42.
	Gaussian terminated normally in 28.75 s. (GS_NEW)
Total QM took 29.90 s.
Submitting electronic structure for step 43.
	Gaussian terminated normally in 29.42 s. (GS_NEW)
Total QM took 30.52 s.
Submitting electronic structure for step 44.
	Gaussian terminated normally in 22.34 s. (GS_NEW)
Total QM took 22.47 s.
Submitting electronic structure for step 45.
	Gaussian terminated normally in 24.33 s. (GS_NEW)
Total QM took 25.76 s.
Submitting electronic structure for step 46.
	Gaussian terminated normally in 24.67 s. (GS_NEW)
Total QM took 24.79 s.
Submitting electronic structure for step 47.
	Gaussian terminated normally in 28.44 s. (GS_NEW)
Total QM took 28.79 s.
Submitting electronic structure for step 48.
	Gaussian terminated normally in 26.30 s. (GS_NEW)
Total QM took 26.68 s.
Submitting electronic structure for step 49.
	Gaussian terminated normally in 22.71 s. (GS_NEW)
Total QM took 23.82 s.
Submitting electronic structure for step 50.
	Gaussian terminated normally in 25.74 s. (GS_NEW)
Total QM took 26.05 s.
Submitting electronic structure for step 51.
	Gaussian terminated normally in 30.72 s. (GS_NEW)
Total QM took 30.84 s.
Submitting electronic structure for step 52.
	Gaussian terminated normally in 28.54 s. (GS_NEW)
Total QM took 28.70 s.
Submitting electronic structure for step 53.
	Gaussian terminated normally in 27.21 s. (GS_NEW)
Total QM took 27.32 s.
Submitting electronic structure for step 54.
	Gaussian terminated normally in 23.52 s. (GS_NEW)
Total QM took 24.47 s.
Submitting electronic structure for step 55.
	Gaussian terminated normally in 22.23 s. (GS_NEW)
Total QM took 22.35 s.
Submitting electronic structure for step 56.
	Gaussian terminated normally in 22.36 s. (GS_NEW)
Total QM took 22.60 s.
Submitting electronic structure for step 57.
	Gaussian terminated normally in 24.96 s. (GS_NEW)
Total QM took 25.74 s.
Submitting electronic structure for step 58.
	Gaussian terminated normally in 21.13 s. (GS_NEW)
Total QM took 21.58 s.
Submitting electronic structure for step 59.
	Gaussian terminated normally in 20.98 s. (GS_NEW)
Total QM took 21.24 s.
Submitting electronic structure for step 60.
	Gaussian terminated normally in 21.22 s. (GS_NEW)
Total QM took 21.35 s.
Submitting electronic structure for step 61.
	Gaussian terminated normally in 22.26 s. (GS_NEW)
Total QM took 22.37 s.
Submitting electronic structure for step 62.
	Gaussian terminated normally in 28.69 s. (GS_NEW)
Total QM took 28.80 s.
Submitting electronic structure for step 63.
	Gaussian terminated normally in 29.61 s. (GS_NEW)
Total QM took 29.84 s.
Submitting electronic structure for step 64.
	Gaussian terminated normally in 22.99 s. (GS_NEW)
Total QM took 24.31 s.
Submitting electronic structure for step 65.
	Gaussian terminated normally in 23.65 s. (GS_NEW)
Total QM took 28.04 s.
Submitting electronic structure for step 66.
	Gaussian terminated normally in 27.29 s. (GS_NEW)
Total QM took 27.76 s.
Submitting electronic structure for step 67.
	Gaussian terminated normally in 30.21 s. (GS_NEW)
Total QM took 31.50 s.
Submitting electronic structure for step 68.
	Gaussian terminated normally in 28.22 s. (GS_NEW)
Total QM took 28.33 s.
Submitting electronic structure for step 69.
	Gaussian terminated normally in 26.11 s. (GS_NEW)
Total QM took 26.22 s.
Submitting electronic structure for step 70.
	Gaussian terminated normally in 26.90 s. (GS_NEW)
Total QM took 27.01 s.
Submitting electronic structure for step 71.
	Gaussian terminated normally in 29.21 s. (GS_NEW)
Total QM took 29.33 s.
Submitting electronic structure for step 72.
	Gaussian terminated normally in 15.90 s. (GS_NEW)
Total QM took 16.14 s.
Submitting electronic structure for step 73.
	Gaussian terminated normally in 21.54 s. (GS_NEW)
Total QM took 21.94 s.
Submitting electronic structure for step 74.
	Gaussian terminated normally in 25.67 s. (GS_NEW)
Total QM took 25.79 s.
Submitting electronic structure for step 75.
	Gaussian terminated normally in 31.97 s. (GS_NEW)
Total QM took 32.08 s.
Submitting electronic structure for step 76.
	Gaussian terminated normally in 20.42 s. (GS_NEW)
Total QM took 20.53 s.
Submitting electronic structure for step 77.
	Gaussian terminated normally in 28.60 s. (GS_NEW)
Total QM took 28.71 s.
Submitting electronic structure for step 78.
	Gaussian terminated normally in 27.45 s. (GS_NEW)
Total QM took 27.78 s.
Submitting electronic structure for step 79.
	Gaussian terminated normally in 33.99 s. (GS_NEW)
Total QM took 34.12 s.
Submitting electronic structure for step 80.
	Gaussian terminated normally in 22.38 s. (GS_NEW)
Total QM took 22.50 s.
Submitting electronic structure for step 81.
	Gaussian terminated normally in 29.77 s. (GS_NEW)
Total QM took 29.88 s.
Submitting electronic structure for step 82.
	Gaussian terminated normally in 27.17 s. (GS_NEW)
Total QM took 27.28 s.
Submitting electronic structure for step 83.
	Gaussian terminated normally in 22.50 s. (GS_NEW)
Total QM took 23.43 s.
Submitting electronic structure for step 84.
	Gaussian terminated normally in 16.65 s. (GS_NEW)
Total QM took 17.37 s.
Submitting electronic structure for step 85.
	Gaussian terminated normally in 24.31 s. (GS_NEW)
Total QM took 24.43 s.
Submitting electronic structure for step 86.
	Gaussian terminated normally in 25.74 s. (GS_NEW)
Total QM took 25.85 s.
Submitting electronic structure for step 87.
	Gaussian terminated normally in 21.70 s. (GS_NEW)
Total QM took 21.82 s.
Submitting electronic structure for step 88.
	Gaussian terminated normally in 27.86 s. (GS_NEW)
Total QM took 27.98 s.
Submitting electronic structure for step 89.
	Gaussian terminated normally in 22.53 s. (GS_NEW)
Total QM took 24.61 s.
Submitting electronic structure for step 90.
	Gaussian terminated normally in 27.27 s. (GS_NEW)
Total QM took 28.11 s.
Submitting electronic structure for step 91.
	Gaussian terminated normally in 25.75 s. (GS_NEW)
Total QM took 25.87 s.
Submitting electronic structure for step 92.
	Gaussian terminated normally in 24.29 s. (GS_NEW)
Total QM took 24.40 s.
Submitting electronic structure for step 93.
	Gaussian terminated normally in 27.19 s. (GS_NEW)
Total QM took 27.31 s.
Submitting electronic structure for step 94.
	Gaussian terminated normally in 24.45 s. (GS_NEW)
Total QM took 24.57 s.
Submitting electronic structure for step 95.
	Gaussian terminated normally in 22.43 s. (GS_NEW)
Total QM took 22.55 s.
Submitting electronic structure for step 96.
	Gaussian terminated normally in 26.64 s. (GS_NEW)
Total QM took 26.75 s.
Submitting electronic structure for step 97.
	Gaussian terminated normally in 25.18 s. (GS_NEW)
Total QM took 25.30 s.
Submitting electronic structure for step 98.
	Gaussian terminated normally in 24.30 s. (GS_NEW)
Total QM took 24.41 s.
Submitting electronic structure for step 99.
	Gaussian terminated normally in 27.86 s. (GS_NEW)
Total QM took 27.97 s.
Submitting electronic structure for step 100.
	Gaussian terminated normally in 21.49 s. (GS_NEW)
Total QM took 21.60 s.
Submitting electronic structure for step 101.
	Gaussian terminated normally in 24.83 s. (GS_NEW)
Total QM took 24.95 s.
Submitting electronic structure for step 102.
	Gaussian terminated normally in 24.85 s. (GS_NEW)
Total QM took 25.31 s.
Submitting electronic structure for step 103.
	Gaussian terminated normally in 22.77 s. (GS_NEW)
Total QM took 22.89 s.
Submitting electronic structure for step 104.
	Gaussian terminated normally in 31.56 s. (GS_NEW)
Total QM took 31.67 s.
Submitting electronic structure for step 105.
	Gaussian terminated normally in 26.93 s. (GS_NEW)
Total QM took 27.04 s.
Submitting electronic structure for step 106.
	Gaussian terminated normally in 24.10 s. (GS_NEW)
Total QM took 24.23 s.
Submitting electronic structure for step 107.
	Gaussian terminated normally in 30.87 s. (GS_NEW)
Total QM took 32.37 s.
Submitting electronic structure for step 108.
	Gaussian terminated normally in 29.42 s. (GS_NEW)
Total QM took 29.54 s.
Submitting electronic structure for step 109.
	Gaussian terminated normally in 19.19 s. (GS_NEW)
Total QM took 19.42 s.
Submitting electronic structure for step 110.
	Gaussian terminated normally in 20.86 s. (GS_NEW)
Total QM took 20.99 s.
Submitting electronic structure for step 111.
	Gaussian terminated normally in 23.57 s. (GS_NEW)
Total QM took 23.68 s.
Submitting electronic structure for step 112.
	Gaussian terminated normally in 27.33 s. (GS_NEW)
Total QM took 27.44 s.
Submitting electronic structure for step 113.
	Gaussian terminated normally in 28.26 s. (GS_NEW)
Total QM took 28.37 s.
Submitting electronic structure for step 114.
	Gaussian terminated normally in 31.36 s. (GS_NEW)
Total QM took 31.47 s.
Submitting electronic structure for step 115.
	Gaussian terminated normally in 86.91 s. (GS_NEW)
Total QM took 87.02 s.
Submitting electronic structure for step 116.
	Gaussian terminated normally in 26.19 s. (GS_NEW)
Total QM took 26.31 s.
Submitting electronic structure for step 117.
	Gaussian terminated normally in 16.81 s. (GS_NEW)
Total QM took 19.34 s.
Submitting electronic structure for step 118.
	Gaussian terminated normally in 26.25 s. (GS_NEW)
Total QM took 26.86 s.
Submitting electronic structure for step 119.
	Gaussian terminated normally in 30.15 s. (GS_NEW)
Total QM took 31.29 s.
Submitting electronic structure for step 120.
	Gaussian terminated normally in 24.71 s. (GS_NEW)
Total QM took 24.82 s.
Submitting electronic structure for step 121.
	Gaussian terminated normally in 24.58 s. (GS_NEW)
Total QM took 24.84 s.
Submitting electronic structure for step 122.
	Gaussian terminated normally in 25.81 s. (GS_NEW)
Total QM took 25.94 s.
Submitting electronic structure for step 123.
	Gaussian terminated normally in 104.96 s. (GS_NEW)
Total QM took 105.07 s.
Submitting electronic structure for step 124.
	Gaussian terminated normally in 30.04 s. (GS_NEW)
Total QM took 30.16 s.
Submitting electronic structure for step 125.
	Gaussian terminated normally in 28.48 s. (GS_NEW)
Total QM took 28.60 s.
Submitting electronic structure for step 126.
	Gaussian terminated normally in 24.31 s. (GS_NEW)
Total QM took 24.43 s.
Submitting electronic structure for step 127.
	Gaussian terminated normally in 22.77 s. (GS_NEW)
Total QM took 22.89 s.
Submitting electronic structure for step 128.
	Gaussian terminated normally in 98.35 s. (GS_NEW)
Total QM took 98.47 s.
Submitting electronic structure for step 129.
	Gaussian terminated normally in 25.24 s. (GS_NEW)
Total QM took 25.92 s.
Submitting electronic structure for step 130.
	Gaussian terminated normally in 26.65 s. (GS_NEW)
Total QM took 26.76 s.
Submitting electronic structure for step 131.
	Gaussian terminated normally in 22.85 s. (GS_NEW)
Total QM took 22.96 s.
Submitting electronic structure for step 132.
	Gaussian terminated normally in 20.49 s. (GS_NEW)
Total QM took 20.60 s.
Submitting electronic structure for step 133.
	Gaussian terminated normally in 22.66 s. (GS_NEW)
Total QM took 22.77 s.
Submitting electronic structure for step 134.
	Gaussian terminated normally in 27.65 s. (GS_NEW)
Total QM took 29.21 s.
Submitting electronic structure for step 135.
	Gaussian terminated normally in 113.77 s. (GS_NEW)
Total QM took 113.88 s.
Submitting electronic structure for step 136.
	Gaussian terminated normally in 25.36 s. (GS_NEW)
Total QM took 25.48 s.
Submitting electronic structure for step 137.
	Gaussian terminated normally in 24.13 s. (GS_NEW)
Total QM took 24.25 s.
Submitting electronic structure for step 138.
	Gaussian terminated normally in 24.44 s. (GS_NEW)
Total QM took 24.56 s.
Submitting electronic structure for step 139.
	Gaussian terminated normally in 29.62 s. (GS_NEW)
Total QM took 29.90 s.
Submitting electronic structure for step 140.
	Gaussian terminated normally in 24.36 s. (GS_NEW)
Total QM took 24.48 s.
Submitting electronic structure for step 141.
	Gaussian terminated normally in 26.51 s. (GS_NEW)
Total QM took 26.62 s.
Submitting electronic structure for step 142.
	Gaussian terminated normally in 27.79 s. (GS_NEW)
Total QM took 27.91 s.
Submitting electronic structure for step 143.
	Gaussian terminated normally in 25.06 s. (GS_NEW)
Total QM took 25.17 s.
Submitting electronic structure for step 144.
	Gaussian terminated normally in 26.17 s. (GS_NEW)
Total QM took 26.74 s.
Submitting electronic structure for step 145.
	Gaussian terminated normally in 19.98 s. (GS_NEW)
Total QM took 20.09 s.
Submitting electronic structure for step 146.
	Gaussian terminated normally in 21.93 s. (GS_NEW)
Total QM took 22.05 s.
Submitting electronic structure for step 147.
	Gaussian terminated normally in 29.21 s. (GS_NEW)
Total QM took 29.32 s.
Submitting electronic structure for step 148.
	Gaussian terminated normally in 26.02 s. (GS_NEW)
Total QM took 26.13 s.
Submitting electronic structure for step 149.
	Gaussian terminated normally in 27.91 s. (GS_NEW)
Total QM took 28.41 s.
Submitting electronic structure for step 150.
	Gaussian terminated normally in 29.54 s. (GS_NEW)
Total QM took 29.66 s.
Submitting electronic structure for step 151.
	Gaussian terminated normally in 24.40 s. (GS_NEW)
Total QM took 24.51 s.
Submitting electronic structure for step 152.
	Gaussian terminated normally in 21.22 s. (GS_NEW)
Total QM took 21.34 s.
Submitting electronic structure for step 153.
	Gaussian terminated normally in 25.21 s. (GS_NEW)
Total QM took 25.48 s.
Submitting electronic structure for step 154.
	Gaussian terminated normally in 27.51 s. (GS_NEW)
Total QM took 30.11 s.
Submitting electronic structure for step 155.
	Gaussian terminated normally in 23.32 s. (GS_NEW)
Total QM took 23.46 s.
Submitting electronic structure for step 156.
	Gaussian terminated normally in 25.21 s. (GS_NEW)
Total QM took 25.32 s.
Submitting electronic structure for step 157.
	Gaussian terminated normally in 19.37 s. (GS_NEW)
Total QM took 20.20 s.
Submitting electronic structure for step 158.
	Gaussian terminated normally in 29.90 s. (GS_NEW)
Total QM took 30.01 s.
Submitting electronic structure for step 159.
	Gaussian terminated normally in 29.75 s. (GS_NEW)
Total QM took 29.86 s.
Submitting electronic structure for step 160.
	Gaussian terminated normally in 27.01 s. (GS_NEW)
Total QM took 27.12 s.
Submitting electronic structure for step 161.
	Gaussian terminated normally in 33.50 s. (GS_NEW)
Total QM took 34.43 s.
Submitting electronic structure for step 162.
	Gaussian terminated normally in 28.06 s. (GS_NEW)
Total QM took 28.17 s.
Submitting electronic structure for step 163.
	Gaussian terminated normally in 22.50 s. (GS_NEW)
Total QM took 22.61 s.
Submitting electronic structure for step 164.
	Gaussian terminated normally in 26.17 s. (GS_NEW)
Total QM took 26.28 s.
Submitting electronic structure for step 165.
	Gaussian terminated normally in 31.26 s. (GS_NEW)
Total QM took 31.37 s.
Submitting electronic structure for step 166.
	Gaussian terminated normally in 22.07 s. (GS_NEW)
Total QM took 22.18 s.
Submitting electronic structure for step 167.
	Gaussian terminated normally in 27.95 s. (GS_NEW)
Total QM took 28.07 s.
Submitting electronic structure for step 168.
	Gaussian terminated normally in 24.34 s. (GS_NEW)
Total QM took 24.46 s.
Submitting electronic structure for step 169.
	Gaussian terminated normally in 28.76 s. (GS_NEW)
Total QM took 29.86 s.
Submitting electronic structure for step 170.
	Gaussian terminated normally in 28.13 s. (GS_NEW)
Total QM took 28.25 s.
Submitting electronic structure for step 171.
	Gaussian terminated normally in 23.60 s. (GS_NEW)
Total QM took 23.71 s.
Submitting electronic structure for step 172.
	Gaussian terminated normally in 29.13 s. (GS_NEW)
Total QM took 30.72 s.
Submitting electronic structure for step 173.
	Gaussian terminated normally in 25.54 s. (GS_NEW)
Total QM took 25.65 s.
Submitting electronic structure for step 174.
	Gaussian terminated normally in 16.96 s. (GS_NEW)
Total QM took 17.07 s.
Submitting electronic structure for step 175.
	Gaussian terminated normally in 22.04 s. (GS_NEW)
Total QM took 22.15 s.
Submitting electronic structure for step 176.
	Gaussian terminated normally in 25.03 s. (GS_NEW)
Total QM took 25.16 s.
Submitting electronic structure for step 177.
	Gaussian terminated normally in 24.01 s. (GS_NEW)
Total QM took 24.27 s.
Submitting electronic structure for step 178.
	Gaussian terminated normally in 25.25 s. (GS_NEW)
Total QM took 25.38 s.
Submitting electronic structure for step 179.
	Gaussian terminated normally in 33.28 s. (GS_NEW)
Total QM took 34.17 s.
Submitting electronic structure for step 180.
	Gaussian terminated normally in 31.60 s. (GS_NEW)
Total QM took 31.71 s.
Submitting electronic structure for step 181.
	Gaussian terminated normally in 29.29 s. (GS_NEW)
Total QM took 29.70 s.
Submitting electronic structure for step 182.
	Gaussian terminated normally in 28.55 s. (GS_NEW)
Total QM took 28.66 s.
Submitting electronic structure for step 183.
	Gaussian terminated normally in 23.70 s. (GS_NEW)
Total QM took 23.81 s.
Submitting electronic structure for step 184.
	Gaussian terminated normally in 30.11 s. (GS_NEW)
Total QM took 30.22 s.
Submitting electronic structure for step 185.
	Gaussian terminated normally in 24.02 s. (GS_NEW)
Total QM took 24.13 s.
Submitting electronic structure for step 186.
	Gaussian terminated normally in 23.18 s. (GS_NEW)
Total QM took 23.29 s.
Submitting electronic structure for step 187.
	Gaussian terminated normally in 26.43 s. (GS_NEW)
Total QM took 26.55 s.
Submitting electronic structure for step 188.
	Gaussian terminated normally in 24.52 s. (GS_NEW)
Total QM took 24.63 s.
Submitting electronic structure for step 189.
	Gaussian terminated normally in 28.57 s. (GS_NEW)
Total QM took 28.68 s.
Submitting electronic structure for step 190.
	Gaussian terminated normally in 19.48 s. (GS_NEW)
Total QM took 19.60 s.
Submitting electronic structure for step 191.
	Gaussian terminated normally in 23.06 s. (GS_NEW)
Total QM took 23.17 s.
Submitting electronic structure for step 192.
	Gaussian terminated normally in 25.78 s. (GS_NEW)
Total QM took 25.97 s.
Submitting electronic structure for step 193.
	Gaussian terminated normally in 24.71 s. (GS_NEW)
Total QM took 24.83 s.
Submitting electronic structure for step 194.
	Gaussian terminated normally in 24.76 s. (GS_NEW)
Total QM took 24.89 s.
Submitting electronic structure for step 195.
	Gaussian terminated normally in 32.79 s. (GS_NEW)
Total QM took 32.90 s.
Submitting electronic structure for step 196.
	Gaussian terminated normally in 26.40 s. (GS_NEW)
Total QM took 26.51 s.
Submitting electronic structure for step 197.
	Gaussian terminated normally in 21.71 s. (GS_NEW)
Total QM took 21.83 s.
Submitting electronic structure for step 198.
	Gaussian terminated normally in 22.38 s. (GS_NEW)
Total QM took 22.49 s.
Submitting electronic structure for step 199.
	Gaussian terminated normally in 25.76 s. (GS_NEW)
Total QM took 26.06 s.
Submitting electronic structure for step 200.
	Gaussian terminated normally in 26.19 s. (GS_NEW)
Total QM took 26.32 s.
Submitting electronic structure for step 201.
	Gaussian terminated normally in 26.43 s. (GS_NEW)
Total QM took 26.54 s.
Submitting electronic structure for step 202.
	Gaussian terminated normally in 28.66 s. (GS_NEW)
Total QM took 28.77 s.
Submitting electronic structure for step 203.
	Gaussian terminated normally in 23.34 s. (GS_NEW)
Total QM took 23.46 s.
Submitting electronic structure for step 204.
	Gaussian terminated normally in 29.45 s. (GS_NEW)
Total QM took 29.56 s.
Submitting electronic structure for step 205.
	Gaussian terminated normally in 34.22 s. (GS_NEW)
Total QM took 34.33 s.
Submitting electronic structure for step 206.
	Gaussian terminated normally in 27.54 s. (GS_NEW)
Total QM took 28.08 s.
Submitting electronic structure for step 207.
	Gaussian terminated normally in 25.33 s. (GS_NEW)
Total QM took 25.44 s.
Submitting electronic structure for step 208.
	Gaussian terminated normally in 27.66 s. (GS_NEW)
Total QM took 27.77 s.
Submitting electronic structure for step 209.
	Gaussian terminated normally in 25.56 s. (GS_NEW)
Total QM took 25.83 s.
Submitting electronic structure for step 210.
	Gaussian terminated normally in 25.51 s. (GS_NEW)
Total QM took 25.63 s.
Submitting electronic structure for step 211.
	Gaussian terminated normally in 26.28 s. (GS_NEW)
Total QM took 26.39 s.
Submitting electronic structure for step 212.
	Gaussian terminated normally in 28.27 s. (GS_NEW)
Total QM took 28.39 s.
Submitting electronic structure for step 213.
	Gaussian terminated normally in 23.97 s. (GS_NEW)
Total QM took 24.80 s.
Submitting electronic structure for step 214.
	Gaussian terminated normally in 23.73 s. (GS_NEW)
Total QM took 23.84 s.
Submitting electronic structure for step 215.
	Gaussian terminated normally in 25.42 s. (GS_NEW)
Total QM took 25.53 s.
Submitting electronic structure for step 216.
	Gaussian terminated normally in 29.73 s. (GS_NEW)
Total QM took 29.84 s.
Submitting electronic structure for step 217.
	Gaussian terminated normally in 23.47 s. (GS_NEW)
Total QM took 23.58 s.
Submitting electronic structure for step 218.
	Gaussian terminated normally in 21.56 s. (GS_NEW)
Total QM took 21.67 s.
Submitting electronic structure for step 219.
	Gaussian terminated normally in 26.70 s. (GS_NEW)
Total QM took 26.81 s.
Submitting electronic structure for step 220.
	Gaussian terminated normally in 25.62 s. (GS_NEW)
Total QM took 25.74 s.
Submitting electronic structure for step 221.
	Gaussian terminated normally in 28.60 s. (GS_NEW)
Total QM took 28.72 s.
Submitting electronic structure for step 222.
	Gaussian terminated normally in 21.27 s. (GS_NEW)
Total QM took 21.39 s.
Submitting electronic structure for step 223.
	Gaussian terminated normally in 22.40 s. (GS_NEW)
Total QM took 22.51 s.
Submitting electronic structure for step 224.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 26.88 s.
Submitting electronic structure for step 225.
	Gaussian terminated normally in 33.49 s. (GS_NEW)
Total QM took 33.60 s.
Submitting electronic structure for step 226.
	Gaussian terminated normally in 17.58 s. (GS_NEW)
Total QM took 17.69 s.
Submitting electronic structure for step 227.
	Gaussian terminated normally in 29.99 s. (GS_NEW)
Total QM took 30.10 s.
Submitting electronic structure for step 228.
	Gaussian terminated normally in 20.97 s. (GS_NEW)
Total QM took 21.09 s.
Submitting electronic structure for step 229.
	Gaussian terminated normally in 23.36 s. (GS_NEW)
Total QM took 23.47 s.
Submitting electronic structure for step 230.
	Gaussian terminated normally in 19.18 s. (GS_NEW)
Total QM took 19.29 s.
Submitting electronic structure for step 231.
	Gaussian terminated normally in 26.94 s. (GS_NEW)
Total QM took 27.07 s.
Submitting electronic structure for step 232.
	Gaussian terminated normally in 23.19 s. (GS_NEW)
Total QM took 23.31 s.
Submitting electronic structure for step 233.
	Gaussian terminated normally in 22.51 s. (GS_NEW)
Total QM took 22.62 s.
Submitting electronic structure for step 234.
	Gaussian terminated normally in 23.22 s. (GS_NEW)
Total QM took 23.34 s.
Submitting electronic structure for step 235.
	Gaussian terminated normally in 24.15 s. (GS_NEW)
Total QM took 24.26 s.
Submitting electronic structure for step 236.
	Gaussian terminated normally in 16.09 s. (GS_NEW)
Total QM took 16.20 s.
Submitting electronic structure for step 237.
	Gaussian terminated normally in 28.52 s. (GS_NEW)
Total QM took 28.63 s.
Submitting electronic structure for step 238.
	Gaussian terminated normally in 24.61 s. (GS_NEW)
Total QM took 24.73 s.
Submitting electronic structure for step 239.
	Gaussian terminated normally in 21.78 s. (GS_NEW)
Total QM took 21.89 s.
Submitting electronic structure for step 240.
	Gaussian terminated normally in 22.00 s. (GS_NEW)
Total QM took 22.11 s.
Submitting electronic structure for step 241.
	Gaussian terminated normally in 22.48 s. (GS_NEW)
Total QM took 22.59 s.
Submitting electronic structure for step 242.
	Gaussian terminated normally in 24.61 s. (GS_NEW)
Total QM took 24.73 s.
Submitting electronic structure for step 243.
	Gaussian terminated normally in 29.23 s. (GS_NEW)
Total QM took 29.68 s.
Submitting electronic structure for step 244.
	Gaussian terminated normally in 26.80 s. (GS_NEW)
Total QM took 26.92 s.
Submitting electronic structure for step 245.
	Gaussian terminated normally in 28.26 s. (GS_NEW)
Total QM took 28.61 s.
Submitting electronic structure for step 246.
	Gaussian terminated normally in 29.06 s. (GS_NEW)
Total QM took 29.17 s.
Submitting electronic structure for step 247.
	Gaussian terminated normally in 22.85 s. (GS_NEW)
Total QM took 23.04 s.
Submitting electronic structure for step 248.
	Gaussian terminated normally in 17.45 s. (GS_NEW)
Total QM took 17.56 s.
Submitting electronic structure for step 249.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 28.93 s.
Submitting electronic structure for step 250.
	Gaussian terminated normally in 24.78 s. (GS_NEW)
Total QM took 25.10 s.
Submitting electronic structure for step 251.
	Gaussian terminated normally in 23.32 s. (GS_NEW)
Total QM took 23.70 s.
Submitting electronic structure for step 252.
	Gaussian terminated normally in 25.28 s. (GS_NEW)
Total QM took 25.39 s.
Submitting electronic structure for step 253.
	Gaussian terminated normally in 26.11 s. (GS_NEW)
Total QM took 26.22 s.
Submitting electronic structure for step 254.
	Gaussian terminated normally in 23.16 s. (GS_NEW)
Total QM took 23.27 s.
Submitting electronic structure for step 255.
	Gaussian terminated normally in 26.91 s. (GS_NEW)
Total QM took 28.41 s.
Submitting electronic structure for step 256.
	Gaussian terminated normally in 27.39 s. (GS_NEW)
Total QM took 27.50 s.
Submitting electronic structure for step 257.
	Gaussian terminated normally in 27.90 s. (GS_NEW)
Total QM took 28.01 s.
Submitting electronic structure for step 258.
	Gaussian terminated normally in 29.54 s. (GS_NEW)
Total QM took 29.65 s.
Submitting electronic structure for step 259.
	Gaussian terminated normally in 29.95 s. (GS_NEW)
Total QM took 30.08 s.
Submitting electronic structure for step 260.
	Gaussian terminated normally in 31.34 s. (GS_NEW)
Total QM took 31.45 s.
Submitting electronic structure for step 261.
	Gaussian terminated normally in 27.38 s. (GS_NEW)
Total QM took 27.49 s.
Submitting electronic structure for step 262.
	Gaussian terminated normally in 25.55 s. (GS_NEW)
Total QM took 25.67 s.
Submitting electronic structure for step 263.
	Gaussian terminated normally in 23.01 s. (GS_NEW)
Total QM took 23.12 s.
Submitting electronic structure for step 264.
	Gaussian terminated normally in 25.72 s. (GS_NEW)
Total QM took 25.83 s.
Submitting electronic structure for step 265.
	Gaussian terminated normally in 29.10 s. (GS_NEW)
Total QM took 29.75 s.
Submitting electronic structure for step 266.
	Gaussian terminated normally in 24.55 s. (GS_NEW)
Total QM took 24.67 s.
Submitting electronic structure for step 267.
	Gaussian terminated normally in 26.41 s. (GS_NEW)
Total QM took 26.52 s.
Submitting electronic structure for step 268.
	Gaussian terminated normally in 25.06 s. (GS_NEW)
Total QM took 25.17 s.
Submitting electronic structure for step 269.
	Gaussian terminated normally in 23.32 s. (GS_NEW)
Total QM took 23.43 s.
Submitting electronic structure for step 270.
	Gaussian terminated normally in 26.15 s. (GS_NEW)
Total QM took 26.27 s.
Submitting electronic structure for step 271.
	Gaussian terminated normally in 28.62 s. (GS_NEW)
Total QM took 28.73 s.
Submitting electronic structure for step 272.
	Gaussian terminated normally in 29.48 s. (GS_NEW)
Total QM took 29.59 s.
Submitting electronic structure for step 273.
	Gaussian terminated normally in 23.86 s. (GS_NEW)
Total QM took 23.97 s.
Submitting electronic structure for step 274.
	Gaussian terminated normally in 26.61 s. (GS_NEW)
Total QM took 29.54 s.
Submitting electronic structure for step 275.
	Gaussian terminated normally in 25.92 s. (GS_NEW)
Total QM took 26.04 s.
Submitting electronic structure for step 276.
	Gaussian terminated normally in 20.10 s. (GS_NEW)
Total QM took 20.33 s.
Submitting electronic structure for step 277.
	Gaussian terminated normally in 24.46 s. (GS_NEW)
Total QM took 24.57 s.
Submitting electronic structure for step 278.
	Gaussian terminated normally in 26.57 s. (GS_NEW)
Total QM took 26.68 s.
Submitting electronic structure for step 279.
	Gaussian terminated normally in 22.36 s. (GS_NEW)
Total QM took 22.48 s.
Submitting electronic structure for step 280.
	Gaussian terminated normally in 27.57 s. (GS_NEW)
Total QM took 27.68 s.
Submitting electronic structure for step 281.
	Gaussian terminated normally in 23.63 s. (GS_NEW)
Total QM took 23.76 s.
Submitting electronic structure for step 282.
	Gaussian terminated normally in 27.50 s. (GS_NEW)
Total QM took 27.62 s.
Submitting electronic structure for step 283.
	Gaussian terminated normally in 20.63 s. (GS_NEW)
Total QM took 20.74 s.
Submitting electronic structure for step 284.
	Gaussian terminated normally in 25.93 s. (GS_NEW)
Total QM took 26.05 s.
Submitting electronic structure for step 285.
	Gaussian terminated normally in 27.52 s. (GS_NEW)
Total QM took 27.91 s.
Submitting electronic structure for step 286.
	Gaussian terminated normally in 16.45 s. (GS_NEW)
Total QM took 16.56 s.
Submitting electronic structure for step 287.
	Gaussian terminated normally in 20.21 s. (GS_NEW)
Total QM took 20.32 s.
Submitting electronic structure for step 288.
	Gaussian terminated normally in 21.30 s. (GS_NEW)
Total QM took 21.41 s.
Submitting electronic structure for step 289.
	Gaussian terminated normally in 27.88 s. (GS_NEW)
Total QM took 27.99 s.
Submitting electronic structure for step 290.
	Gaussian terminated normally in 25.19 s. (GS_NEW)
Total QM took 25.31 s.
Submitting electronic structure for step 291.
	Gaussian terminated normally in 30.37 s. (GS_NEW)
Total QM took 30.48 s.
Submitting electronic structure for step 292.
	Gaussian terminated normally in 21.68 s. (GS_NEW)
Total QM took 22.28 s.
Submitting electronic structure for step 293.
	Gaussian terminated normally in 25.20 s. (GS_NEW)
Total QM took 25.31 s.
Submitting electronic structure for step 294.
	Gaussian terminated normally in 22.72 s. (GS_NEW)
Total QM took 22.85 s.
Submitting electronic structure for step 295.
	Gaussian terminated normally in 26.39 s. (GS_NEW)
Total QM took 26.51 s.
Submitting electronic structure for step 296.
	Gaussian terminated normally in 30.53 s. (GS_NEW)
Total QM took 30.91 s.
Submitting electronic structure for step 297.
	Gaussian terminated normally in 23.42 s. (GS_NEW)
Total QM took 23.78 s.
Submitting electronic structure for step 298.
	Gaussian terminated normally in 25.20 s. (GS_NEW)
Total QM took 25.47 s.
Submitting electronic structure for step 299.
	Gaussian terminated normally in 20.00 s. (GS_NEW)
Total QM took 20.12 s.
Submitting electronic structure for step 300.
	Gaussian terminated normally in 23.51 s. (GS_NEW)
Total QM took 25.70 s.
Submitting electronic structure for step 301.
	Gaussian terminated normally in 26.43 s. (GS_NEW)
Total QM took 26.54 s.
Submitting electronic structure for step 302.
	Gaussian terminated normally in 24.34 s. (GS_NEW)
Total QM took 24.72 s.
Submitting electronic structure for step 303.
	Gaussian terminated normally in 34.85 s. (GS_NEW)
Total QM took 34.97 s.
Submitting electronic structure for step 304.
	Gaussian terminated normally in 26.73 s. (GS_NEW)
Total QM took 26.84 s.
Submitting electronic structure for step 305.
	Gaussian terminated normally in 23.53 s. (GS_NEW)
Total QM took 23.64 s.
Submitting electronic structure for step 306.
	Gaussian terminated normally in 23.86 s. (GS_NEW)
Total QM took 23.98 s.
Submitting electronic structure for step 307.
	Gaussian terminated normally in 24.37 s. (GS_NEW)
Total QM took 24.49 s.
Submitting electronic structure for step 308.
	Gaussian terminated normally in 25.28 s. (GS_NEW)
Total QM took 25.40 s.
Submitting electronic structure for step 309.
	Gaussian terminated normally in 30.94 s. (GS_NEW)
Total QM took 31.06 s.
Submitting electronic structure for step 310.
	Gaussian terminated normally in 24.46 s. (GS_NEW)
Total QM took 24.66 s.
Submitting electronic structure for step 311.
	Gaussian terminated normally in 22.07 s. (GS_NEW)
Total QM took 22.19 s.
Submitting electronic structure for step 312.
	Gaussian terminated normally in 25.86 s. (GS_NEW)
Total QM took 25.97 s.
Submitting electronic structure for step 313.
	Gaussian terminated normally in 24.24 s. (GS_NEW)
Total QM took 25.20 s.
Submitting electronic structure for step 314.
	Gaussian terminated normally in 25.12 s. (GS_NEW)
Total QM took 25.23 s.
Submitting electronic structure for step 315.
	Gaussian terminated normally in 24.30 s. (GS_NEW)
Total QM took 24.41 s.
Submitting electronic structure for step 316.
	Gaussian terminated normally in 27.06 s. (GS_NEW)
Total QM took 27.18 s.
Submitting electronic structure for step 317.
	Gaussian terminated normally in 30.70 s. (GS_NEW)
Total QM took 31.71 s.
Submitting electronic structure for step 318.
	Gaussian terminated normally in 29.94 s. (GS_NEW)
Total QM took 30.05 s.
Submitting electronic structure for step 319.
	Gaussian terminated normally in 28.73 s. (GS_NEW)
Total QM took 28.84 s.
Submitting electronic structure for step 320.
	Gaussian terminated normally in 29.43 s. (GS_NEW)
Total QM took 30.40 s.
Submitting electronic structure for step 321.
	Gaussian terminated normally in 26.69 s. (GS_NEW)
Total QM took 26.95 s.
Submitting electronic structure for step 322.
	Gaussian terminated normally in 24.88 s. (GS_NEW)
Total QM took 25.00 s.
Submitting electronic structure for step 323.
	Gaussian terminated normally in 23.31 s. (GS_NEW)
Total QM took 23.85 s.
Submitting electronic structure for step 324.
	Gaussian terminated normally in 27.34 s. (GS_NEW)
Total QM took 27.67 s.
Submitting electronic structure for step 325.
	Gaussian terminated normally in 24.93 s. (GS_NEW)
Total QM took 25.05 s.
Submitting electronic structure for step 326.
	Gaussian terminated normally in 26.51 s. (GS_NEW)
Total QM took 26.62 s.
Submitting electronic structure for step 327.
	Gaussian terminated normally in 25.80 s. (GS_NEW)
Total QM took 25.92 s.
Submitting electronic structure for step 328.
	Gaussian terminated normally in 31.94 s. (GS_NEW)
Total QM took 32.05 s.
Submitting electronic structure for step 329.
	Gaussian terminated normally in 27.56 s. (GS_NEW)
Total QM took 27.67 s.
Submitting electronic structure for step 330.
	Gaussian terminated normally in 22.88 s. (GS_NEW)
Total QM took 22.99 s.
Submitting electronic structure for step 331.
	Gaussian terminated normally in 25.63 s. (GS_NEW)
Total QM took 26.55 s.
Submitting electronic structure for step 332.
	Gaussian terminated normally in 22.93 s. (GS_NEW)
Total QM took 23.04 s.
Submitting electronic structure for step 333.
	Gaussian terminated normally in 31.72 s. (GS_NEW)
Total QM took 31.86 s.
Submitting electronic structure for step 334.
	Gaussian terminated normally in 29.22 s. (GS_NEW)
Total QM took 29.34 s.
Submitting electronic structure for step 335.
	Gaussian terminated normally in 31.21 s. (GS_NEW)
Total QM took 32.15 s.
Submitting electronic structure for step 336.
	Gaussian terminated normally in 27.01 s. (GS_NEW)
Total QM took 27.37 s.
Submitting electronic structure for step 337.
	Gaussian terminated normally in 27.73 s. (GS_NEW)
Total QM took 27.85 s.
Submitting electronic structure for step 338.
	Gaussian terminated normally in 25.83 s. (GS_NEW)
Total QM took 26.39 s.
Submitting electronic structure for step 339.
	Gaussian terminated normally in 30.03 s. (GS_NEW)
Total QM took 30.14 s.
Submitting electronic structure for step 340.
	Gaussian terminated normally in 24.80 s. (GS_NEW)
Total QM took 24.92 s.
Submitting electronic structure for step 341.
	Gaussian terminated normally in 18.68 s. (GS_NEW)
Total QM took 18.80 s.
Submitting electronic structure for step 342.
	Gaussian terminated normally in 24.30 s. (GS_NEW)
Total QM took 24.41 s.
Submitting electronic structure for step 343.
	Gaussian terminated normally in 23.80 s. (GS_NEW)
Total QM took 23.91 s.
Submitting electronic structure for step 344.
	Gaussian terminated normally in 23.32 s. (GS_NEW)
Total QM took 23.44 s.
Submitting electronic structure for step 345.
	Gaussian terminated normally in 31.78 s. (GS_NEW)
Total QM took 32.12 s.
Submitting electronic structure for step 346.
	Gaussian terminated normally in 26.87 s. (GS_NEW)
Total QM took 26.98 s.
Submitting electronic structure for step 347.
	Gaussian terminated normally in 22.61 s. (GS_NEW)
Total QM took 22.72 s.
Submitting electronic structure for step 348.
	Gaussian terminated normally in 29.05 s. (GS_NEW)
Total QM took 30.91 s.
Submitting electronic structure for step 349.
	Gaussian terminated normally in 24.65 s. (GS_NEW)
Total QM took 24.76 s.
Submitting electronic structure for step 350.
	Gaussian terminated normally in 23.50 s. (GS_NEW)
Total QM took 23.61 s.
Submitting electronic structure for step 351.
	Gaussian terminated normally in 25.80 s. (GS_NEW)
Total QM took 25.92 s.
Submitting electronic structure for step 352.
	Gaussian terminated normally in 23.29 s. (GS_NEW)
Total QM took 23.68 s.
Submitting electronic structure for step 353.
	Gaussian terminated normally in 23.54 s. (GS_NEW)
Total QM took 23.65 s.
Submitting electronic structure for step 354.
	Gaussian terminated normally in 30.36 s. (GS_NEW)
Total QM took 30.47 s.
Submitting electronic structure for step 355.
	Gaussian terminated normally in 26.86 s. (GS_NEW)
Total QM took 26.97 s.
Submitting electronic structure for step 356.
	Gaussian terminated normally in 29.74 s. (GS_NEW)
Total QM took 29.85 s.
Submitting electronic structure for step 357.
	Gaussian terminated normally in 29.38 s. (GS_NEW)
Total QM took 29.50 s.
Submitting electronic structure for step 358.
	Gaussian terminated normally in 23.44 s. (GS_NEW)
Total QM took 23.56 s.
Submitting electronic structure for step 359.
	Gaussian terminated normally in 25.39 s. (GS_NEW)
Total QM took 25.50 s.
Submitting electronic structure for step 360.
	Gaussian terminated normally in 24.05 s. (GS_NEW)
Total QM took 24.16 s.
Submitting electronic structure for step 361.
	Gaussian terminated normally in 18.93 s. (GS_NEW)
Total QM took 19.04 s.
Submitting electronic structure for step 362.
	Gaussian terminated normally in 23.90 s. (GS_NEW)
Total QM took 24.02 s.
Submitting electronic structure for step 363.
	Gaussian terminated normally in 25.34 s. (GS_NEW)
Total QM took 25.45 s.
Submitting electronic structure for step 364.
	Gaussian terminated normally in 22.70 s. (GS_NEW)
Total QM took 25.30 s.
Submitting electronic structure for step 365.
	Gaussian terminated normally in 25.42 s. (GS_NEW)
Total QM took 25.54 s.
Submitting electronic structure for step 366.
	Gaussian terminated normally in 26.31 s. (GS_NEW)
Total QM took 26.42 s.
Submitting electronic structure for step 367.
	Gaussian terminated normally in 27.79 s. (GS_NEW)
Total QM took 29.96 s.
Submitting electronic structure for step 368.
	Gaussian terminated normally in 25.86 s. (GS_NEW)
Total QM took 25.98 s.
Submitting electronic structure for step 369.
	Gaussian terminated normally in 24.40 s. (GS_NEW)
Total QM took 25.14 s.
Submitting electronic structure for step 370.
	Gaussian terminated normally in 29.18 s. (GS_NEW)
Total QM took 29.30 s.
Submitting electronic structure for step 371.
	Gaussian terminated normally in 25.64 s. (GS_NEW)
Total QM took 25.76 s.
Submitting electronic structure for step 372.
	Gaussian terminated normally in 21.94 s. (GS_NEW)
Total QM took 22.05 s.
Submitting electronic structure for step 373.
	Gaussian terminated normally in 27.85 s. (GS_NEW)
Total QM took 27.96 s.
Submitting electronic structure for step 374.
	Gaussian terminated normally in 28.67 s. (GS_NEW)
Total QM took 29.27 s.
Submitting electronic structure for step 375.
	Gaussian terminated normally in 31.87 s. (GS_NEW)
Total QM took 31.98 s.
Submitting electronic structure for step 376.
	Gaussian terminated normally in 23.53 s. (GS_NEW)
Total QM took 23.64 s.
Submitting electronic structure for step 377.
	Gaussian terminated normally in 21.91 s. (GS_NEW)
Total QM took 22.02 s.
Submitting electronic structure for step 378.
	Gaussian terminated normally in 26.64 s. (GS_NEW)
Total QM took 26.75 s.
Submitting electronic structure for step 379.
	Gaussian terminated normally in 26.71 s. (GS_NEW)
Total QM took 26.83 s.
Submitting electronic structure for step 380.
	Gaussian terminated normally in 25.34 s. (GS_NEW)
Total QM took 26.05 s.
Submitting electronic structure for step 381.
	Gaussian terminated normally in 26.41 s. (GS_NEW)
Total QM took 26.52 s.
Submitting electronic structure for step 382.
	Gaussian terminated normally in 26.03 s. (GS_NEW)
Total QM took 26.59 s.
Submitting electronic structure for step 383.
	Gaussian terminated normally in 21.46 s. (GS_NEW)
Total QM took 21.57 s.
Submitting electronic structure for step 384.
	Gaussian terminated normally in 22.72 s. (GS_NEW)
Total QM took 22.83 s.
Submitting electronic structure for step 385.
	Gaussian terminated normally in 28.00 s. (GS_NEW)
Total QM took 28.12 s.
Submitting electronic structure for step 386.
	Gaussian terminated normally in 27.04 s. (GS_NEW)
Total QM took 27.16 s.
Submitting electronic structure for step 387.
	Gaussian terminated normally in 26.09 s. (GS_NEW)
Total QM took 26.22 s.
Submitting electronic structure for step 388.
	Gaussian terminated normally in 25.49 s. (GS_NEW)
Total QM took 25.61 s.
Submitting electronic structure for step 389.
	Gaussian terminated normally in 28.23 s. (GS_NEW)
Total QM took 28.36 s.
Submitting electronic structure for step 390.
	Gaussian terminated normally in 24.07 s. (GS_NEW)
Total QM took 25.03 s.
Submitting electronic structure for step 391.
	Gaussian terminated normally in 31.94 s. (GS_NEW)
Total QM took 32.06 s.
Submitting electronic structure for step 392.
	Gaussian terminated normally in 28.72 s. (GS_NEW)
Total QM took 28.84 s.
Submitting electronic structure for step 393.
	Gaussian terminated normally in 24.21 s. (GS_NEW)
Total QM took 24.32 s.
Submitting electronic structure for step 394.
	Gaussian terminated normally in 21.45 s. (GS_NEW)
Total QM took 21.56 s.
Submitting electronic structure for step 395.
	Gaussian terminated normally in 25.34 s. (GS_NEW)
Total QM took 25.45 s.
Submitting electronic structure for step 396.
	Gaussian terminated normally in 26.90 s. (GS_NEW)
Total QM took 27.01 s.
Submitting electronic structure for step 397.
	Gaussian terminated normally in 27.53 s. (GS_NEW)
Total QM took 27.64 s.
Submitting electronic structure for step 398.
	Gaussian terminated normally in 27.62 s. (GS_NEW)
Total QM took 27.73 s.
Submitting electronic structure for step 399.
	Gaussian terminated normally in 24.10 s. (GS_NEW)
Total QM took 24.22 s.
Submitting electronic structure for step 400.
	Gaussian terminated normally in 23.47 s. (GS_NEW)
Total QM took 23.58 s.
Submitting electronic structure for step 401.
	Gaussian terminated normally in 27.52 s. (GS_NEW)
Total QM took 27.63 s.
Submitting electronic structure for step 402.
	Gaussian terminated normally in 21.13 s. (GS_NEW)
Total QM took 21.24 s.
Submitting electronic structure for step 403.
	Gaussian terminated normally in 18.46 s. (GS_NEW)
Total QM took 18.57 s.
Submitting electronic structure for step 404.
	Gaussian terminated normally in 27.31 s. (GS_NEW)
Total QM took 27.42 s.
Submitting electronic structure for step 405.
	Gaussian terminated normally in 25.03 s. (GS_NEW)
Total QM took 25.14 s.
Submitting electronic structure for step 406.
	Gaussian terminated normally in 29.47 s. (GS_NEW)
Total QM took 29.58 s.
Submitting electronic structure for step 407.
	Gaussian terminated normally in 29.23 s. (GS_NEW)
Total QM took 29.34 s.
Submitting electronic structure for step 408.
	Gaussian terminated normally in 27.07 s. (GS_NEW)
Total QM took 27.20 s.
Submitting electronic structure for step 409.
	Gaussian terminated normally in 25.58 s. (GS_NEW)
Total QM took 25.70 s.
Submitting electronic structure for step 410.
	Gaussian terminated normally in 31.20 s. (GS_NEW)
Total QM took 31.31 s.
Submitting electronic structure for step 411.
	Gaussian terminated normally in 27.23 s. (GS_NEW)
Total QM took 27.34 s.
Submitting electronic structure for step 412.
	Gaussian terminated normally in 24.29 s. (GS_NEW)
Total QM took 24.40 s.
Submitting electronic structure for step 413.
	Gaussian terminated normally in 26.42 s. (GS_NEW)
Total QM took 27.32 s.
Submitting electronic structure for step 414.
	Gaussian terminated normally in 27.31 s. (GS_NEW)
Total QM took 27.42 s.
Submitting electronic structure for step 415.
	Gaussian terminated normally in 25.04 s. (GS_NEW)
Total QM took 25.15 s.
Submitting electronic structure for step 416.
	Gaussian terminated normally in 20.60 s. (GS_NEW)
Total QM took 20.71 s.
Submitting electronic structure for step 417.
	Gaussian terminated normally in 28.90 s. (GS_NEW)
Total QM took 29.37 s.
Submitting electronic structure for step 418.
	Gaussian terminated normally in 27.52 s. (GS_NEW)
Total QM took 27.64 s.
Submitting electronic structure for step 419.
	Gaussian terminated normally in 23.33 s. (GS_NEW)
Total QM took 24.70 s.
Submitting electronic structure for step 420.
	Gaussian terminated normally in 25.17 s. (GS_NEW)
Total QM took 25.28 s.
Submitting electronic structure for step 421.
	Gaussian terminated normally in 28.42 s. (GS_NEW)
Total QM took 28.54 s.
Submitting electronic structure for step 422.
	Gaussian terminated normally in 25.73 s. (GS_NEW)
Total QM took 28.10 s.
Submitting electronic structure for step 423.
	Gaussian terminated normally in 25.66 s. (GS_NEW)
Total QM took 26.88 s.
Submitting electronic structure for step 424.
	Gaussian terminated normally in 27.80 s. (GS_NEW)
Total QM took 27.91 s.
Submitting electronic structure for step 425.
	Gaussian terminated normally in 27.49 s. (GS_NEW)
Total QM took 27.60 s.
Submitting electronic structure for step 426.
	Gaussian terminated normally in 26.16 s. (GS_NEW)
Total QM took 26.29 s.
Submitting electronic structure for step 427.
	Gaussian terminated normally in 24.54 s. (GS_NEW)
Total QM took 24.66 s.
Submitting electronic structure for step 428.
	Gaussian terminated normally in 25.20 s. (GS_NEW)
Total QM took 25.31 s.
Submitting electronic structure for step 429.
	Gaussian terminated normally in 24.36 s. (GS_NEW)
Total QM took 25.01 s.
Submitting electronic structure for step 430.
	Gaussian terminated normally in 27.42 s. (GS_NEW)
Total QM took 27.53 s.
Submitting electronic structure for step 431.
	Gaussian terminated normally in 27.58 s. (GS_NEW)
Total QM took 27.69 s.
Submitting electronic structure for step 432.
	Gaussian terminated normally in 26.83 s. (GS_NEW)
Total QM took 26.95 s.
Submitting electronic structure for step 433.
	Gaussian terminated normally in 26.24 s. (GS_NEW)
Total QM took 26.35 s.
Submitting electronic structure for step 434.
	Gaussian terminated normally in 27.93 s. (GS_NEW)
Total QM took 28.05 s.
Submitting electronic structure for step 435.
	Gaussian terminated normally in 23.92 s. (GS_NEW)
Total QM took 24.38 s.
Submitting electronic structure for step 436.
	Gaussian terminated normally in 30.36 s. (GS_NEW)
Total QM took 30.48 s.
Submitting electronic structure for step 437.
	Gaussian terminated normally in 21.55 s. (GS_NEW)
Total QM took 21.67 s.
Submitting electronic structure for step 438.
	Gaussian terminated normally in 27.99 s. (GS_NEW)
Total QM took 28.48 s.
Submitting electronic structure for step 439.
	Gaussian terminated normally in 26.50 s. (GS_NEW)
Total QM took 27.09 s.
Submitting electronic structure for step 440.
	Gaussian terminated normally in 25.03 s. (GS_NEW)
Total QM took 25.60 s.
Submitting electronic structure for step 441.
	Gaussian terminated normally in 19.16 s. (GS_NEW)
Total QM took 19.27 s.
Submitting electronic structure for step 442.
	Gaussian terminated normally in 22.93 s. (GS_NEW)
Total QM took 23.04 s.
Submitting electronic structure for step 443.
	Gaussian terminated normally in 20.94 s. (GS_NEW)
Total QM took 21.05 s.
Submitting electronic structure for step 444.
	Gaussian terminated normally in 26.58 s. (GS_NEW)
Total QM took 26.69 s.
Submitting electronic structure for step 445.
	Gaussian terminated normally in 25.55 s. (GS_NEW)
Total QM took 25.68 s.
Submitting electronic structure for step 446.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 26.87 s.
Submitting electronic structure for step 447.
	Gaussian terminated normally in 17.76 s. (GS_NEW)
Total QM took 17.87 s.
Submitting electronic structure for step 448.
	Gaussian terminated normally in 20.01 s. (GS_NEW)
Total QM took 20.35 s.
Submitting electronic structure for step 449.
	Gaussian terminated normally in 26.07 s. (GS_NEW)
Total QM took 26.18 s.
Submitting electronic structure for step 450.
	Gaussian terminated normally in 24.38 s. (GS_NEW)
Total QM took 24.49 s.
Submitting electronic structure for step 451.
	Gaussian terminated normally in 29.22 s. (GS_NEW)
Total QM took 29.33 s.
Submitting electronic structure for step 452.
	Gaussian terminated normally in 26.93 s. (GS_NEW)
Total QM took 27.04 s.
Submitting electronic structure for step 453.
	Gaussian terminated normally in 32.06 s. (GS_NEW)
Total QM took 32.18 s.
Submitting electronic structure for step 454.
	Gaussian terminated normally in 23.13 s. (GS_NEW)
Total QM took 23.90 s.
Submitting electronic structure for step 455.
	Gaussian terminated normally in 26.16 s. (GS_NEW)
Total QM took 26.95 s.
Submitting electronic structure for step 456.
	Gaussian terminated normally in 33.55 s. (GS_NEW)
Total QM took 33.66 s.
Submitting electronic structure for step 457.
	Gaussian terminated normally in 26.89 s. (GS_NEW)
Total QM took 27.01 s.
Submitting electronic structure for step 458.
	Gaussian terminated normally in 22.67 s. (GS_NEW)
Total QM took 22.79 s.
Submitting electronic structure for step 459.
	Gaussian terminated normally in 21.89 s. (GS_NEW)
Total QM took 22.00 s.
Submitting electronic structure for step 460.
	Gaussian terminated normally in 24.94 s. (GS_NEW)
Total QM took 25.05 s.
Submitting electronic structure for step 461.
	Gaussian terminated normally in 25.78 s. (GS_NEW)
Total QM took 25.89 s.
Submitting electronic structure for step 462.
	Gaussian terminated normally in 25.75 s. (GS_NEW)
Total QM took 25.86 s.
Submitting electronic structure for step 463.
	Gaussian terminated normally in 29.15 s. (GS_NEW)
Total QM took 29.26 s.
Submitting electronic structure for step 464.
	Gaussian terminated normally in 23.56 s. (GS_NEW)
Total QM took 23.71 s.
Submitting electronic structure for step 465.
	Gaussian terminated normally in 22.43 s. (GS_NEW)
Total QM took 22.55 s.
Submitting electronic structure for step 466.
	Gaussian terminated normally in 30.66 s. (GS_NEW)
Total QM took 30.77 s.
Submitting electronic structure for step 467.
	Gaussian terminated normally in 27.11 s. (GS_NEW)
Total QM took 27.22 s.
Submitting electronic structure for step 468.
	Gaussian terminated normally in 33.94 s. (GS_NEW)
Total QM took 34.53 s.
Submitting electronic structure for step 469.
	Gaussian terminated normally in 26.37 s. (GS_NEW)
Total QM took 26.49 s.
Submitting electronic structure for step 470.
	Gaussian terminated normally in 23.21 s. (GS_NEW)
Total QM took 23.33 s.
Submitting electronic structure for step 471.
	Gaussian terminated normally in 27.79 s. (GS_NEW)
Total QM took 28.10 s.
Submitting electronic structure for step 472.
	Gaussian terminated normally in 25.42 s. (GS_NEW)
Total QM took 25.54 s.
Submitting electronic structure for step 473.
	Gaussian terminated normally in 28.02 s. (GS_NEW)
Total QM took 28.13 s.
Submitting electronic structure for step 474.
	Gaussian terminated normally in 24.94 s. (GS_NEW)
Total QM took 25.05 s.
Submitting electronic structure for step 475.
	Gaussian terminated normally in 30.42 s. (GS_NEW)
Total QM took 30.53 s.
Submitting electronic structure for step 476.
	Gaussian terminated normally in 30.30 s. (GS_NEW)
Total QM took 30.41 s.
Submitting electronic structure for step 477.
	Gaussian terminated normally in 26.15 s. (GS_NEW)
Total QM took 26.26 s.
Submitting electronic structure for step 478.
	Gaussian terminated normally in 24.37 s. (GS_NEW)
Total QM took 24.48 s.
Submitting electronic structure for step 479.
	Gaussian terminated normally in 26.63 s. (GS_NEW)
Total QM took 26.74 s.
Submitting electronic structure for step 480.
	Gaussian terminated normally in 23.89 s. (GS_NEW)
Total QM took 24.00 s.
Submitting electronic structure for step 481.
	Gaussian terminated normally in 24.93 s. (GS_NEW)
Total QM took 25.04 s.
Submitting electronic structure for step 482.
	Gaussian terminated normally in 31.32 s. (GS_NEW)
Total QM took 31.43 s.
Submitting electronic structure for step 483.
	Gaussian terminated normally in 23.28 s. (GS_NEW)
Total QM took 23.39 s.
Submitting electronic structure for step 484.
	Gaussian terminated normally in 29.02 s. (GS_NEW)
Total QM took 29.13 s.
Submitting electronic structure for step 485.
	Gaussian terminated normally in 26.58 s. (GS_NEW)
Total QM took 26.69 s.
Submitting electronic structure for step 486.
	Gaussian terminated normally in 26.36 s. (GS_NEW)
Total QM took 26.47 s.
Submitting electronic structure for step 487.
	Gaussian terminated normally in 21.61 s. (GS_NEW)
Total QM took 21.72 s.
Submitting electronic structure for step 488.
	Gaussian terminated normally in 27.29 s. (GS_NEW)
Total QM took 27.40 s.
Submitting electronic structure for step 489.
	Gaussian terminated normally in 27.73 s. (GS_NEW)
Total QM took 27.85 s.
Submitting electronic structure for step 490.
	Gaussian terminated normally in 29.01 s. (GS_NEW)
Total QM took 29.12 s.
Submitting electronic structure for step 491.
	Gaussian terminated normally in 21.95 s. (GS_NEW)
Total QM took 22.06 s.
Submitting electronic structure for step 492.
	Gaussian terminated normally in 24.77 s. (GS_NEW)
Total QM took 24.88 s.
Submitting electronic structure for step 493.
	Gaussian terminated normally in 22.30 s. (GS_NEW)
Total QM took 22.59 s.
Submitting electronic structure for step 494.
	Gaussian terminated normally in 33.99 s. (GS_NEW)
Total QM took 34.14 s.
Submitting electronic structure for step 495.
	Gaussian terminated normally in 27.33 s. (GS_NEW)
Total QM took 27.44 s.
Submitting electronic structure for step 496.
	Gaussian terminated normally in 26.79 s. (GS_NEW)
Total QM took 27.69 s.
Submitting electronic structure for step 497.
	Gaussian terminated normally in 23.85 s. (GS_NEW)
Total QM took 23.96 s.
Submitting electronic structure for step 498.
	Gaussian terminated normally in 33.18 s. (GS_NEW)
Total QM took 33.29 s.
Submitting electronic structure for step 499.
	Gaussian terminated normally in 26.41 s. (GS_NEW)
Total QM took 26.53 s.
Submitting electronic structure for step 500.
	Gaussian terminated normally in 27.22 s. (GS_NEW)
Total QM took 27.34 s.
Submitting electronic structure for step 501.
	Gaussian terminated normally in 22.88 s. (GS_NEW)
Total QM took 22.99 s.
Submitting electronic structure for step 502.
	Gaussian terminated normally in 22.62 s. (GS_NEW)
Total QM took 23.57 s.
Submitting electronic structure for step 503.
	Gaussian terminated normally in 27.01 s. (GS_NEW)
Total QM took 27.12 s.
Submitting electronic structure for step 504.
	Gaussian terminated normally in 23.60 s. (GS_NEW)
Total QM took 23.71 s.
Submitting electronic structure for step 505.
	Gaussian terminated normally in 27.60 s. (GS_NEW)
Total QM took 27.71 s.
Submitting electronic structure for step 506.
	Gaussian terminated normally in 24.90 s. (GS_NEW)
Total QM took 25.01 s.
Submitting electronic structure for step 507.
	Gaussian terminated normally in 28.47 s. (GS_NEW)
Total QM took 28.58 s.
Submitting electronic structure for step 508.
	Gaussian terminated normally in 25.66 s. (GS_NEW)
Total QM took 25.77 s.
Submitting electronic structure for step 509.
	Gaussian terminated normally in 28.28 s. (GS_NEW)
Total QM took 28.40 s.
Submitting electronic structure for step 510.
	Gaussian terminated normally in 21.88 s. (GS_NEW)
Total QM took 21.99 s.
Submitting electronic structure for step 511.
	Gaussian terminated normally in 26.38 s. (GS_NEW)
Total QM took 26.50 s.
Submitting electronic structure for step 512.
	Gaussian terminated normally in 28.00 s. (GS_NEW)
Total QM took 29.09 s.
Submitting electronic structure for step 513.
	Gaussian terminated normally in 22.40 s. (GS_NEW)
Total QM took 22.52 s.
Submitting electronic structure for step 514.
	Gaussian terminated normally in 22.39 s. (GS_NEW)
Total QM took 22.51 s.
Submitting electronic structure for step 515.
	Gaussian terminated normally in 29.68 s. (GS_NEW)
Total QM took 29.79 s.
Submitting electronic structure for step 516.
	Gaussian terminated normally in 21.25 s. (GS_NEW)
Total QM took 21.37 s.
Submitting electronic structure for step 517.
	Gaussian terminated normally in 32.18 s. (GS_NEW)
Total QM took 32.29 s.
Submitting electronic structure for step 518.
	Gaussian terminated normally in 22.63 s. (GS_NEW)
Total QM took 22.74 s.
Submitting electronic structure for step 519.
	Gaussian terminated normally in 36.11 s. (GS_NEW)
Total QM took 37.01 s.
Submitting electronic structure for step 520.
	Gaussian terminated normally in 29.28 s. (GS_NEW)
Total QM took 29.40 s.
Submitting electronic structure for step 521.
	Gaussian terminated normally in 24.73 s. (GS_NEW)
Total QM took 24.85 s.
Submitting electronic structure for step 522.
	Gaussian terminated normally in 22.07 s. (GS_NEW)
Total QM took 22.18 s.
Submitting electronic structure for step 523.
	Gaussian terminated normally in 20.28 s. (GS_NEW)
Total QM took 20.39 s.
Submitting electronic structure for step 524.
	Gaussian terminated normally in 28.58 s. (GS_NEW)
Total QM took 28.70 s.
Submitting electronic structure for step 525.
	Gaussian terminated normally in 28.15 s. (GS_NEW)
Total QM took 28.26 s.
Submitting electronic structure for step 526.
	Gaussian terminated normally in 27.30 s. (GS_NEW)
Total QM took 27.41 s.
Submitting electronic structure for step 527.
	Gaussian terminated normally in 28.14 s. (GS_NEW)
Total QM took 28.25 s.
Submitting electronic structure for step 528.
	Gaussian terminated normally in 19.88 s. (GS_NEW)
Total QM took 19.99 s.
Submitting electronic structure for step 529.
	Gaussian terminated normally in 24.67 s. (GS_NEW)
Total QM took 24.78 s.
Submitting electronic structure for step 530.
	Gaussian terminated normally in 22.20 s. (GS_NEW)
Total QM took 22.31 s.
Submitting electronic structure for step 531.
	Gaussian terminated normally in 27.11 s. (GS_NEW)
Total QM took 27.22 s.
Submitting electronic structure for step 532.
	Gaussian terminated normally in 36.73 s. (GS_NEW)
Total QM took 36.85 s.
Submitting electronic structure for step 533.
	Gaussian terminated normally in 22.75 s. (GS_NEW)
Total QM took 22.86 s.
Submitting electronic structure for step 534.
	Gaussian terminated normally in 26.71 s. (GS_NEW)
Total QM took 26.82 s.
Submitting electronic structure for step 535.
	Gaussian terminated normally in 30.04 s. (GS_NEW)
Total QM took 30.15 s.
Submitting electronic structure for step 536.
	Gaussian terminated normally in 27.93 s. (GS_NEW)
Total QM took 28.04 s.
Submitting electronic structure for step 537.
	Gaussian terminated normally in 23.79 s. (GS_NEW)
Total QM took 23.90 s.
Submitting electronic structure for step 538.
	Gaussian terminated normally in 25.22 s. (GS_NEW)
Total QM took 25.33 s.
Submitting electronic structure for step 539.
	Gaussian terminated normally in 26.82 s. (GS_NEW)
Total QM took 26.94 s.
Submitting electronic structure for step 540.
	Gaussian terminated normally in 25.32 s. (GS_NEW)
Total QM took 25.44 s.
Submitting electronic structure for step 541.
	Gaussian terminated normally in 26.92 s. (GS_NEW)
Total QM took 27.04 s.
Submitting electronic structure for step 542.
	Gaussian terminated normally in 26.19 s. (GS_NEW)
Total QM took 26.30 s.
Submitting electronic structure for step 543.
	Gaussian terminated normally in 24.14 s. (GS_NEW)
Total QM took 24.25 s.
Submitting electronic structure for step 544.
	Gaussian terminated normally in 25.22 s. (GS_NEW)
Total QM took 25.34 s.
Submitting electronic structure for step 545.
	Gaussian terminated normally in 23.47 s. (GS_NEW)
Total QM took 23.59 s.
Submitting electronic structure for step 546.
	Gaussian terminated normally in 31.46 s. (GS_NEW)
Total QM took 31.58 s.
Submitting electronic structure for step 547.
	Gaussian terminated normally in 27.06 s. (GS_NEW)
Total QM took 27.18 s.
Submitting electronic structure for step 548.
	Gaussian terminated normally in 27.12 s. (GS_NEW)
Total QM took 27.71 s.
Submitting electronic structure for step 549.
	Gaussian terminated normally in 25.49 s. (GS_NEW)
Total QM took 25.60 s.
Submitting electronic structure for step 550.
	Gaussian terminated normally in 27.65 s. (GS_NEW)
Total QM took 27.76 s.
Submitting electronic structure for step 551.
	Gaussian terminated normally in 20.78 s. (GS_NEW)
Total QM took 20.90 s.
Submitting electronic structure for step 552.
	Gaussian terminated normally in 28.29 s. (GS_NEW)
Total QM took 28.43 s.
Submitting electronic structure for step 553.
	Gaussian terminated normally in 21.85 s. (GS_NEW)
Total QM took 21.96 s.
Submitting electronic structure for step 554.
	Gaussian terminated normally in 30.03 s. (GS_NEW)
Total QM took 30.15 s.
Submitting electronic structure for step 555.
	Gaussian terminated normally in 29.82 s. (GS_NEW)
Total QM took 29.94 s.
Submitting electronic structure for step 556.
	Gaussian terminated normally in 29.94 s. (GS_NEW)
Total QM took 30.06 s.
Submitting electronic structure for step 557.
	Gaussian terminated normally in 26.70 s. (GS_NEW)
Total QM took 26.82 s.
Submitting electronic structure for step 558.
	Gaussian terminated normally in 32.43 s. (GS_NEW)
Total QM took 32.54 s.
Submitting electronic structure for step 559.
	Gaussian terminated normally in 20.93 s. (GS_NEW)
Total QM took 21.05 s.
Submitting electronic structure for step 560.
	Gaussian terminated normally in 21.66 s. (GS_NEW)
Total QM took 21.77 s.
Submitting electronic structure for step 561.
	Gaussian terminated normally in 27.12 s. (GS_NEW)
Total QM took 27.23 s.
Submitting electronic structure for step 562.
	Gaussian terminated normally in 19.99 s. (GS_NEW)
Total QM took 21.82 s.
Submitting electronic structure for step 563.
	Gaussian terminated normally in 24.69 s. (GS_NEW)
Total QM took 24.82 s.
Submitting electronic structure for step 564.
	Gaussian terminated normally in 25.74 s. (GS_NEW)
Total QM took 25.86 s.
Submitting electronic structure for step 565.
	Gaussian terminated normally in 30.00 s. (GS_NEW)
Total QM took 30.11 s.
Submitting electronic structure for step 566.
	Gaussian terminated normally in 26.09 s. (GS_NEW)
Total QM took 26.44 s.
Submitting electronic structure for step 567.
	Gaussian terminated normally in 23.93 s. (GS_NEW)
Total QM took 24.04 s.
Submitting electronic structure for step 568.
	Gaussian terminated normally in 25.91 s. (GS_NEW)
Total QM took 26.85 s.
Submitting electronic structure for step 569.
	Gaussian terminated normally in 22.30 s. (GS_NEW)
Total QM took 22.41 s.
Submitting electronic structure for step 570.
	Gaussian terminated normally in 23.78 s. (GS_NEW)
Total QM took 24.68 s.
Submitting electronic structure for step 571.
	Gaussian terminated normally in 20.76 s. (GS_NEW)
Total QM took 21.38 s.
Submitting electronic structure for step 572.
	Gaussian terminated normally in 30.87 s. (GS_NEW)
Total QM took 31.00 s.
Submitting electronic structure for step 573.
	Gaussian terminated normally in 23.53 s. (GS_NEW)
Total QM took 23.64 s.
Submitting electronic structure for step 574.
	Gaussian terminated normally in 28.99 s. (GS_NEW)
Total QM took 29.11 s.
Submitting electronic structure for step 575.
	Gaussian terminated normally in 27.17 s. (GS_NEW)
Total QM took 27.28 s.
Submitting electronic structure for step 576.
	Gaussian terminated normally in 22.39 s. (GS_NEW)
Total QM took 22.52 s.
Submitting electronic structure for step 577.
	Gaussian terminated normally in 21.34 s. (GS_NEW)
Total QM took 21.45 s.
Submitting electronic structure for step 578.
	Gaussian terminated normally in 30.51 s. (GS_NEW)
Total QM took 30.64 s.
Submitting electronic structure for step 579.
	Gaussian terminated normally in 25.84 s. (GS_NEW)
Total QM took 26.62 s.
Submitting electronic structure for step 580.
	Gaussian terminated normally in 27.87 s. (GS_NEW)
Total QM took 27.98 s.
Submitting electronic structure for step 581.
	Gaussian terminated normally in 22.86 s. (GS_NEW)
Total QM took 22.97 s.
Submitting electronic structure for step 582.
	Gaussian terminated normally in 25.91 s. (GS_NEW)
Total QM took 26.23 s.
Submitting electronic structure for step 583.
	Gaussian terminated normally in 22.70 s. (GS_NEW)
Total QM took 22.82 s.
Submitting electronic structure for step 584.
	Gaussian terminated normally in 26.30 s. (GS_NEW)
Total QM took 26.41 s.
Submitting electronic structure for step 585.
	Gaussian terminated normally in 26.83 s. (GS_NEW)
Total QM took 26.94 s.
Submitting electronic structure for step 586.
	Gaussian terminated normally in 31.95 s. (GS_NEW)
Total QM took 32.07 s.
Submitting electronic structure for step 587.
	Gaussian terminated normally in 20.45 s. (GS_NEW)
Total QM took 20.56 s.
Submitting electronic structure for step 588.
	Gaussian terminated normally in 24.89 s. (GS_NEW)
Total QM took 25.85 s.
Submitting electronic structure for step 589.
	Gaussian terminated normally in 32.74 s. (GS_NEW)
Total QM took 32.85 s.
Submitting electronic structure for step 590.
	Gaussian terminated normally in 24.45 s. (GS_NEW)
Total QM took 24.57 s.
Submitting electronic structure for step 591.
	Gaussian terminated normally in 26.98 s. (GS_NEW)
Total QM took 28.16 s.
Submitting electronic structure for step 592.
	Gaussian terminated normally in 19.07 s. (GS_NEW)
Total QM took 19.47 s.
Submitting electronic structure for step 593.
	Gaussian terminated normally in 27.55 s. (GS_NEW)
Total QM took 27.66 s.
Submitting electronic structure for step 594.
	Gaussian terminated normally in 22.98 s. (GS_NEW)
Total QM took 23.11 s.
Submitting electronic structure for step 595.
	Gaussian terminated normally in 26.35 s. (GS_NEW)
Total QM took 26.47 s.
Submitting electronic structure for step 596.
	Gaussian terminated normally in 25.34 s. (GS_NEW)
Total QM took 25.59 s.
Submitting electronic structure for step 597.
	Gaussian terminated normally in 25.71 s. (GS_NEW)
Total QM took 27.54 s.
Submitting electronic structure for step 598.
	Gaussian terminated normally in 23.67 s. (GS_NEW)
Total QM took 23.79 s.
Submitting electronic structure for step 599.
	Gaussian terminated normally in 27.35 s. (GS_NEW)
Total QM took 27.47 s.
Submitting electronic structure for step 600.
	Gaussian terminated normally in 24.97 s. (GS_NEW)
Total QM took 25.73 s.
Submitting electronic structure for step 601.
	Gaussian terminated normally in 25.87 s. (GS_NEW)
Total QM took 25.99 s.
Submitting electronic structure for step 602.
	Gaussian terminated normally in 32.57 s. (GS_NEW)
Total QM took 32.69 s.
Submitting electronic structure for step 603.
	Gaussian terminated normally in 19.42 s. (GS_NEW)
Total QM took 19.55 s.
Submitting electronic structure for step 604.
	Gaussian terminated normally in 23.61 s. (GS_NEW)
Total QM took 24.36 s.
Submitting electronic structure for step 605.
	Gaussian terminated normally in 21.12 s. (GS_NEW)
Total QM took 21.24 s.
Submitting electronic structure for step 606.
	Gaussian terminated normally in 29.95 s. (GS_NEW)
Total QM took 30.06 s.
Submitting electronic structure for step 607.
	Gaussian terminated normally in 29.61 s. (GS_NEW)
Total QM took 29.74 s.
Submitting electronic structure for step 608.
	Gaussian terminated normally in 21.67 s. (GS_NEW)
Total QM took 21.79 s.
Submitting electronic structure for step 609.
	Gaussian terminated normally in 19.37 s. (GS_NEW)
Total QM took 19.50 s.
Submitting electronic structure for step 610.
	Gaussian terminated normally in 22.11 s. (GS_NEW)
Total QM took 22.23 s.
Submitting electronic structure for step 611.
	Gaussian terminated normally in 25.72 s. (GS_NEW)
Total QM took 25.84 s.
Submitting electronic structure for step 612.
	Gaussian terminated normally in 23.53 s. (GS_NEW)
Total QM took 23.64 s.
Submitting electronic structure for step 613.
	Gaussian terminated normally in 24.77 s. (GS_NEW)
Total QM took 24.88 s.
Submitting electronic structure for step 614.
	Gaussian terminated normally in 29.23 s. (GS_NEW)
Total QM took 29.35 s.
Submitting electronic structure for step 615.
	Gaussian terminated normally in 25.87 s. (GS_NEW)
Total QM took 25.98 s.
Submitting electronic structure for step 616.
	Gaussian terminated normally in 27.81 s. (GS_NEW)
Total QM took 27.92 s.
Submitting electronic structure for step 617.
	Gaussian terminated normally in 24.72 s. (GS_NEW)
Total QM took 24.83 s.
Submitting electronic structure for step 618.
	Gaussian terminated normally in 30.00 s. (GS_NEW)
Total QM took 30.45 s.
Submitting electronic structure for step 619.
	Gaussian terminated normally in 24.54 s. (GS_NEW)
Total QM took 24.65 s.
Submitting electronic structure for step 620.
	Gaussian terminated normally in 21.76 s. (GS_NEW)
Total QM took 21.88 s.
Submitting electronic structure for step 621.
	Gaussian terminated normally in 29.92 s. (GS_NEW)
Total QM took 30.09 s.
Submitting electronic structure for step 622.
	Gaussian terminated normally in 31.86 s. (GS_NEW)
Total QM took 31.97 s.
Submitting electronic structure for step 623.
	Gaussian terminated normally in 27.38 s. (GS_NEW)
Total QM took 27.50 s.
Submitting electronic structure for step 624.
	Gaussian terminated normally in 26.73 s. (GS_NEW)
Total QM took 26.85 s.
Submitting electronic structure for step 625.
	Gaussian terminated normally in 22.72 s. (GS_NEW)
Total QM took 22.90 s.
Submitting electronic structure for step 626.
	Gaussian terminated normally in 26.02 s. (GS_NEW)
Total QM took 26.78 s.
Submitting electronic structure for step 627.
	Gaussian terminated normally in 28.77 s. (GS_NEW)
Total QM took 28.91 s.
Submitting electronic structure for step 628.
	Gaussian terminated normally in 25.26 s. (GS_NEW)
Total QM took 25.38 s.
Submitting electronic structure for step 629.
	Gaussian terminated normally in 25.71 s. (GS_NEW)
Total QM took 25.83 s.
Submitting electronic structure for step 630.
	Gaussian terminated normally in 26.37 s. (GS_NEW)
Total QM took 26.48 s.
Submitting electronic structure for step 631.
	Gaussian terminated normally in 21.18 s. (GS_NEW)
Total QM took 21.31 s.
Submitting electronic structure for step 632.
	Gaussian terminated normally in 35.02 s. (GS_NEW)
Total QM took 35.14 s.
Submitting electronic structure for step 633.
	Gaussian terminated normally in 23.82 s. (GS_NEW)
Total QM took 24.35 s.
Submitting electronic structure for step 634.
	Gaussian terminated normally in 25.90 s. (GS_NEW)
Total QM took 26.01 s.
Submitting electronic structure for step 635.
	Gaussian terminated normally in 21.82 s. (GS_NEW)
Total QM took 21.94 s.
Submitting electronic structure for step 636.
	Gaussian terminated normally in 26.80 s. (GS_NEW)
Total QM took 26.91 s.
Submitting electronic structure for step 637.
	Gaussian terminated normally in 24.93 s. (GS_NEW)
Total QM took 25.04 s.
Submitting electronic structure for step 638.
	Gaussian terminated normally in 23.34 s. (GS_NEW)
Total QM took 23.46 s.
Submitting electronic structure for step 639.
	Gaussian terminated normally in 25.55 s. (GS_NEW)
Total QM took 25.66 s.
Submitting electronic structure for step 640.
	Gaussian terminated normally in 24.45 s. (GS_NEW)
Total QM took 24.57 s.
Submitting electronic structure for step 641.
	Gaussian terminated normally in 31.34 s. (GS_NEW)
Total QM took 31.45 s.
Submitting electronic structure for step 642.
	Gaussian terminated normally in 26.23 s. (GS_NEW)
Total QM took 26.34 s.
Submitting electronic structure for step 643.
	Gaussian terminated normally in 33.99 s. (GS_NEW)
Total QM took 38.45 s.
Submitting electronic structure for step 644.
	Gaussian terminated normally in 38.03 s. (GS_NEW)
Total QM took 38.15 s.
Submitting electronic structure for step 645.
	Gaussian terminated normally in 112.79 s. (GS_NEW)
Total QM took 112.90 s.
Submitting electronic structure for step 646.
	Gaussian terminated normally in 24.69 s. (GS_NEW)
Total QM took 24.81 s.
Submitting electronic structure for step 647.
	Gaussian terminated normally in 30.53 s. (GS_NEW)
Total QM took 30.64 s.
Submitting electronic structure for step 648.
	Gaussian terminated normally in 21.57 s. (GS_NEW)
Total QM took 21.76 s.
Submitting electronic structure for step 649.
	Gaussian terminated normally in 28.85 s. (GS_NEW)
Total QM took 28.97 s.
Submitting electronic structure for step 650.
	Gaussian terminated normally in 25.16 s. (GS_NEW)
Total QM took 25.27 s.
Submitting electronic structure for step 651.
	Gaussian terminated normally in 21.80 s. (GS_NEW)
Total QM took 21.91 s.
Submitting electronic structure for step 652.
	Gaussian terminated normally in 30.56 s. (GS_NEW)
Total QM took 30.67 s.
Submitting electronic structure for step 653.
	Gaussian terminated normally in 27.08 s. (GS_NEW)
Total QM took 28.35 s.
Submitting electronic structure for step 654.
	Gaussian terminated normally in 86.61 s. (GS_NEW)
Total QM took 86.73 s.
Submitting electronic structure for step 655.
	Gaussian terminated normally in 26.82 s. (GS_NEW)
Total QM took 26.93 s.
Submitting electronic structure for step 656.
	Gaussian terminated normally in 27.48 s. (GS_NEW)
Total QM took 27.60 s.
Submitting electronic structure for step 657.
	Gaussian terminated normally in 25.66 s. (GS_NEW)
Total QM took 25.78 s.
Submitting electronic structure for step 658.
	Gaussian terminated normally in 25.43 s. (GS_NEW)
Total QM took 25.54 s.
Submitting electronic structure for step 659.
	Gaussian terminated normally in 26.55 s. (GS_NEW)
Total QM took 26.66 s.
Submitting electronic structure for step 660.
	Gaussian terminated normally in 27.13 s. (GS_NEW)
Total QM took 27.24 s.
Submitting electronic structure for step 661.
	Gaussian terminated normally in 25.84 s. (GS_NEW)
Total QM took 25.95 s.
Submitting electronic structure for step 662.
	Gaussian terminated normally in 30.11 s. (GS_NEW)
Total QM took 30.22 s.
Submitting electronic structure for step 663.
	Gaussian terminated normally in 23.33 s. (GS_NEW)
Total QM took 23.44 s.
Submitting electronic structure for step 664.
	Gaussian terminated normally in 24.09 s. (GS_NEW)
Total QM took 24.21 s.
Submitting electronic structure for step 665.
	Gaussian terminated normally in 25.82 s. (GS_NEW)
Total QM took 25.93 s.
Submitting electronic structure for step 666.
	Gaussian terminated normally in 19.89 s. (GS_NEW)
Total QM took 20.00 s.
Submitting electronic structure for step 667.
	Gaussian terminated normally in 25.99 s. (GS_NEW)
Total QM took 26.20 s.
Submitting electronic structure for step 668.
	Gaussian terminated normally in 28.37 s. (GS_NEW)
Total QM took 28.48 s.
Submitting electronic structure for step 669.
	Gaussian terminated normally in 22.97 s. (GS_NEW)
Total QM took 23.08 s.
Submitting electronic structure for step 670.
	Gaussian terminated normally in 28.72 s. (GS_NEW)
Total QM took 28.83 s.
Submitting electronic structure for step 671.
	Gaussian terminated normally in 26.43 s. (GS_NEW)
Total QM took 26.54 s.
Submitting electronic structure for step 672.
	Gaussian terminated normally in 24.97 s. (GS_NEW)
Total QM took 25.40 s.
Submitting electronic structure for step 673.
	Gaussian terminated normally in 31.49 s. (GS_NEW)
Total QM took 31.61 s.
Submitting electronic structure for step 674.
	Gaussian terminated normally in 22.96 s. (GS_NEW)
Total QM took 23.07 s.
Submitting electronic structure for step 675.
	Gaussian terminated normally in 27.47 s. (GS_NEW)
Total QM took 27.58 s.
Submitting electronic structure for step 676.
	Gaussian terminated normally in 27.58 s. (GS_NEW)
Total QM took 27.69 s.
Submitting electronic structure for step 677.
	Gaussian terminated normally in 31.38 s. (GS_NEW)
Total QM took 31.81 s.
Submitting electronic structure for step 678.
	Gaussian terminated normally in 26.77 s. (GS_NEW)
Total QM took 26.89 s.
Submitting electronic structure for step 679.
	Gaussian terminated normally in 28.46 s. (GS_NEW)
Total QM took 29.64 s.
Submitting electronic structure for step 680.
	Gaussian terminated normally in 25.13 s. (GS_NEW)
Total QM took 25.24 s.
Submitting electronic structure for step 681.
	Gaussian terminated normally in 23.52 s. (GS_NEW)
Total QM took 23.63 s.
Submitting electronic structure for step 682.
	Gaussian terminated normally in 28.90 s. (GS_NEW)
Total QM took 29.02 s.
Submitting electronic structure for step 683.
	Gaussian terminated normally in 28.13 s. (GS_NEW)
Total QM took 28.24 s.
Submitting electronic structure for step 684.
	Gaussian terminated normally in 19.66 s. (GS_NEW)
Total QM took 19.96 s.
Submitting electronic structure for step 685.
	Gaussian terminated normally in 24.02 s. (GS_NEW)
Total QM took 24.60 s.
Submitting electronic structure for step 686.
	Gaussian terminated normally in 31.53 s. (GS_NEW)
Total QM took 31.64 s.
Submitting electronic structure for step 687.
	Gaussian terminated normally in 23.47 s. (GS_NEW)
Total QM took 23.59 s.
Submitting electronic structure for step 688.
	Gaussian terminated normally in 25.20 s. (GS_NEW)
Total QM took 25.32 s.
Submitting electronic structure for step 689.
	Gaussian terminated normally in 25.31 s. (GS_NEW)
Total QM took 25.42 s.
Submitting electronic structure for step 690.
	Gaussian terminated normally in 26.75 s. (GS_NEW)
Total QM took 26.87 s.
Submitting electronic structure for step 691.
	Gaussian terminated normally in 25.42 s. (GS_NEW)
Total QM took 25.53 s.
Submitting electronic structure for step 692.
	Gaussian terminated normally in 26.19 s. (GS_NEW)
Total QM took 26.31 s.
Submitting electronic structure for step 693.
	Gaussian terminated normally in 21.01 s. (GS_NEW)
Total QM took 21.13 s.
Submitting electronic structure for step 694.
	Gaussian terminated normally in 22.59 s. (GS_NEW)
Total QM took 22.70 s.
Submitting electronic structure for step 695.
	Gaussian terminated normally in 31.52 s. (GS_NEW)
Total QM took 31.63 s.
Submitting electronic structure for step 696.
	Gaussian terminated normally in 29.46 s. (GS_NEW)
Total QM took 29.57 s.
Submitting electronic structure for step 697.
	Gaussian terminated normally in 26.74 s. (GS_NEW)
Total QM took 26.85 s.
Submitting electronic structure for step 698.
	Gaussian terminated normally in 27.94 s. (GS_NEW)
Total QM took 28.07 s.
Submitting electronic structure for step 699.
	Gaussian terminated normally in 21.85 s. (GS_NEW)
Total QM took 22.48 s.
Submitting electronic structure for step 700.
	Gaussian terminated normally in 29.19 s. (GS_NEW)
Total QM took 29.31 s.
Submitting electronic structure for step 701.
	Gaussian terminated normally in 27.05 s. (GS_NEW)
Total QM took 27.16 s.
Submitting electronic structure for step 702.
	Gaussian terminated normally in 17.83 s. (GS_NEW)
Total QM took 17.94 s.
Submitting electronic structure for step 703.
	Gaussian terminated normally in 30.48 s. (GS_NEW)
Total QM took 30.59 s.
Submitting electronic structure for step 704.
	Gaussian terminated normally in 25.97 s. (GS_NEW)
Total QM took 26.09 s.
Submitting electronic structure for step 705.
	Gaussian terminated normally in 27.70 s. (GS_NEW)
Total QM took 27.81 s.
Submitting electronic structure for step 706.
	Gaussian terminated normally in 24.44 s. (GS_NEW)
Total QM took 25.15 s.
Submitting electronic structure for step 707.
	Gaussian terminated normally in 23.97 s. (GS_NEW)
Total QM took 24.09 s.
Submitting electronic structure for step 708.
	Gaussian terminated normally in 27.29 s. (GS_NEW)
Total QM took 27.40 s.
Submitting electronic structure for step 709.
	Gaussian terminated normally in 27.06 s. (GS_NEW)
Total QM took 27.17 s.
Submitting electronic structure for step 710.
	Gaussian terminated normally in 20.43 s. (GS_NEW)
Total QM took 20.54 s.
Submitting electronic structure for step 711.
	Gaussian terminated normally in 24.81 s. (GS_NEW)
Total QM took 25.76 s.
Submitting electronic structure for step 712.
	Gaussian terminated normally in 23.12 s. (GS_NEW)
Total QM took 23.37 s.
Submitting electronic structure for step 713.
	Gaussian terminated normally in 24.61 s. (GS_NEW)
Total QM took 24.72 s.
Submitting electronic structure for step 714.
	Gaussian terminated normally in 30.75 s. (GS_NEW)
Total QM took 30.86 s.
Submitting electronic structure for step 715.
	Gaussian terminated normally in 27.04 s. (GS_NEW)
Total QM took 27.15 s.
Submitting electronic structure for step 716.
	Gaussian terminated normally in 30.50 s. (GS_NEW)
Total QM took 30.62 s.
Submitting electronic structure for step 717.
	Gaussian terminated normally in 28.55 s. (GS_NEW)
Total QM took 28.67 s.
Submitting electronic structure for step 718.
	Gaussian terminated normally in 27.50 s. (GS_NEW)
Total QM took 28.04 s.
Submitting electronic structure for step 719.
	Gaussian terminated normally in 21.66 s. (GS_NEW)
Total QM took 21.95 s.
Submitting electronic structure for step 720.
	Gaussian terminated normally in 26.42 s. (GS_NEW)
Total QM took 26.53 s.
Submitting electronic structure for step 721.
	Gaussian terminated normally in 27.44 s. (GS_NEW)
Total QM took 27.56 s.
Submitting electronic structure for step 722.
	Gaussian terminated normally in 24.30 s. (GS_NEW)
Total QM took 24.41 s.
Submitting electronic structure for step 723.
	Gaussian terminated normally in 25.75 s. (GS_NEW)
Total QM took 25.86 s.
Submitting electronic structure for step 724.
	Gaussian terminated normally in 25.52 s. (GS_NEW)
Total QM took 25.63 s.
Submitting electronic structure for step 725.
	Gaussian terminated normally in 26.03 s. (GS_NEW)
Total QM took 26.15 s.
Submitting electronic structure for step 726.
	Gaussian terminated normally in 22.39 s. (GS_NEW)
Total QM took 22.50 s.
Submitting electronic structure for step 727.
	Gaussian terminated normally in 25.26 s. (GS_NEW)
Total QM took 25.37 s.
Submitting electronic structure for step 728.
	Gaussian terminated normally in 21.96 s. (GS_NEW)
Total QM took 22.21 s.
Submitting electronic structure for step 729.
	Gaussian terminated normally in 27.99 s. (GS_NEW)
Total QM took 28.10 s.
Submitting electronic structure for step 730.
	Gaussian terminated normally in 22.77 s. (GS_NEW)
Total QM took 22.88 s.
Submitting electronic structure for step 731.
	Gaussian terminated normally in 22.26 s. (GS_NEW)
Total QM took 22.37 s.
Submitting electronic structure for step 732.
	Gaussian terminated normally in 23.47 s. (GS_NEW)
Total QM took 23.58 s.
Submitting electronic structure for step 733.
	Gaussian terminated normally in 26.14 s. (GS_NEW)
Total QM took 26.25 s.
Submitting electronic structure for step 734.
	Gaussian terminated normally in 26.84 s. (GS_NEW)
Total QM took 26.96 s.
Submitting electronic structure for step 735.
	Gaussian terminated normally in 22.78 s. (GS_NEW)
Total QM took 24.01 s.
Submitting electronic structure for step 736.
	Gaussian terminated normally in 24.12 s. (GS_NEW)
Total QM took 24.25 s.
Submitting electronic structure for step 737.
	Gaussian terminated normally in 23.26 s. (GS_NEW)
Total QM took 23.37 s.
Submitting electronic structure for step 738.
	Gaussian terminated normally in 22.40 s. (GS_NEW)
Total QM took 22.51 s.
Submitting electronic structure for step 739.
	Gaussian terminated normally in 26.45 s. (GS_NEW)
Total QM took 26.57 s.
Submitting electronic structure for step 740.
	Gaussian terminated normally in 24.13 s. (GS_NEW)
Total QM took 24.31 s.
Submitting electronic structure for step 741.
	Gaussian terminated normally in 24.70 s. (GS_NEW)
Total QM took 24.81 s.
Submitting electronic structure for step 742.
	Gaussian terminated normally in 17.45 s. (GS_NEW)
Total QM took 17.57 s.
Submitting electronic structure for step 743.
	Gaussian terminated normally in 22.08 s. (GS_NEW)
Total QM took 22.71 s.
Submitting electronic structure for step 744.
	Gaussian terminated normally in 32.63 s. (GS_NEW)
Total QM took 32.74 s.
Submitting electronic structure for step 745.
	Gaussian terminated normally in 21.49 s. (GS_NEW)
Total QM took 21.61 s.
Submitting electronic structure for step 746.
	Gaussian terminated normally in 19.36 s. (GS_NEW)
Total QM took 19.47 s.
Submitting electronic structure for step 747.
	Gaussian terminated normally in 20.14 s. (GS_NEW)
Total QM took 20.25 s.
Submitting electronic structure for step 748.
	Gaussian terminated normally in 26.22 s. (GS_NEW)
Total QM took 26.33 s.
Submitting electronic structure for step 749.
	Gaussian terminated normally in 26.61 s. (GS_NEW)
Total QM took 26.72 s.
Submitting electronic structure for step 750.
	Gaussian terminated normally in 27.87 s. (GS_NEW)
Total QM took 27.98 s.
Submitting electronic structure for step 751.
	Gaussian terminated normally in 28.46 s. (GS_NEW)
Total QM took 28.57 s.
Submitting electronic structure for step 752.
	Gaussian terminated normally in 25.44 s. (GS_NEW)
Total QM took 25.57 s.
Submitting electronic structure for step 753.
	Gaussian terminated normally in 20.71 s. (GS_NEW)
Total QM took 20.83 s.
Submitting electronic structure for step 754.
	Gaussian terminated normally in 27.59 s. (GS_NEW)
Total QM took 27.70 s.
Submitting electronic structure for step 755.
	Gaussian terminated normally in 30.10 s. (GS_NEW)
Total QM took 30.70 s.
Submitting electronic structure for step 756.
	Gaussian terminated normally in 24.48 s. (GS_NEW)
Total QM took 24.59 s.
Submitting electronic structure for step 757.
	Gaussian terminated normally in 25.04 s. (GS_NEW)
Total QM took 25.15 s.
Submitting electronic structure for step 758.
	Gaussian terminated normally in 25.58 s. (GS_NEW)
Total QM took 25.69 s.
Submitting electronic structure for step 759.
	Gaussian terminated normally in 24.73 s. (GS_NEW)
Total QM took 24.85 s.
Submitting electronic structure for step 760.
	Gaussian terminated normally in 26.70 s. (GS_NEW)
Total QM took 26.81 s.
Submitting electronic structure for step 761.
	Gaussian terminated normally in 21.89 s. (GS_NEW)
Total QM took 22.44 s.
Submitting electronic structure for step 762.
	Gaussian terminated normally in 23.60 s. (GS_NEW)
Total QM took 23.96 s.
Submitting electronic structure for step 763.
	Gaussian terminated normally in 26.79 s. (GS_NEW)
Total QM took 26.91 s.
Submitting electronic structure for step 764.
	Gaussian terminated normally in 30.37 s. (GS_NEW)
Total QM took 30.48 s.
Submitting electronic structure for step 765.
	Gaussian terminated normally in 28.73 s. (GS_NEW)
Total QM took 28.84 s.
Submitting electronic structure for step 766.
	Gaussian terminated normally in 22.00 s. (GS_NEW)
Total QM took 22.11 s.
Submitting electronic structure for step 767.
	Gaussian terminated normally in 27.17 s. (GS_NEW)
Total QM took 27.69 s.
Submitting electronic structure for step 768.
	Gaussian terminated normally in 29.75 s. (GS_NEW)
Total QM took 29.86 s.
Submitting electronic structure for step 769.
	Gaussian terminated normally in 24.86 s. (GS_NEW)
Total QM took 24.98 s.
Submitting electronic structure for step 770.
	Gaussian terminated normally in 26.32 s. (GS_NEW)
Total QM took 26.44 s.
Submitting electronic structure for step 771.
	Gaussian terminated normally in 27.08 s. (GS_NEW)
Total QM took 27.19 s.
Submitting electronic structure for step 772.
	Gaussian terminated normally in 29.97 s. (GS_NEW)
Total QM took 30.25 s.
Submitting electronic structure for step 773.
	Gaussian terminated normally in 26.26 s. (GS_NEW)
Total QM took 26.52 s.
Submitting electronic structure for step 774.
	Gaussian terminated normally in 33.14 s. (GS_NEW)
Total QM took 33.25 s.
Submitting electronic structure for step 775.
	Gaussian terminated normally in 26.55 s. (GS_NEW)
Total QM took 26.66 s.
Submitting electronic structure for step 776.
	Gaussian terminated normally in 27.85 s. (GS_NEW)
Total QM took 27.97 s.
Submitting electronic structure for step 777.
	Gaussian terminated normally in 27.89 s. (GS_NEW)
Total QM took 28.01 s.
Submitting electronic structure for step 778.
	Gaussian terminated normally in 26.93 s. (GS_NEW)
Total QM took 27.04 s.
Submitting electronic structure for step 779.
	Gaussian terminated normally in 28.32 s. (GS_NEW)
Total QM took 28.44 s.
Submitting electronic structure for step 780.
	Gaussian terminated normally in 36.33 s. (GS_NEW)
Total QM took 36.44 s.
Submitting electronic structure for step 781.
	Gaussian terminated normally in 20.93 s. (GS_NEW)
Total QM took 21.04 s.
Submitting electronic structure for step 782.
	Gaussian terminated normally in 15.00 s. (GS_NEW)
Total QM took 89.61 s.
Submitting electronic structure for step 783.
	Gaussian terminated normally in 98.57 s. (GS_NEW)
Total QM took 98.76 s.
Submitting electronic structure for step 784.
	Gaussian terminated normally in 27.09 s. (GS_NEW)
Total QM took 27.21 s.
Submitting electronic structure for step 785.
	Gaussian terminated normally in 27.06 s. (GS_NEW)
Total QM took 27.18 s.
Submitting electronic structure for step 786.
	Gaussian terminated normally in 27.59 s. (GS_NEW)
Total QM took 27.71 s.
Submitting electronic structure for step 787.
	Gaussian terminated normally in 23.80 s. (GS_NEW)
Total QM took 23.91 s.
Submitting electronic structure for step 788.
	Gaussian terminated normally in 31.46 s. (GS_NEW)
Total QM took 31.57 s.
Submitting electronic structure for step 789.
	Gaussian terminated normally in 23.83 s. (GS_NEW)
Total QM took 23.94 s.
Submitting electronic structure for step 790.
	Gaussian terminated normally in 30.97 s. (GS_NEW)
Total QM took 31.09 s.
Submitting electronic structure for step 791.
	Gaussian terminated normally in 106.15 s. (GS_NEW)
Total QM took 106.26 s.
Submitting electronic structure for step 792.
	Gaussian terminated normally in 26.37 s. (GS_NEW)
Total QM took 26.49 s.
Submitting electronic structure for step 793.
	Gaussian terminated normally in 20.35 s. (GS_NEW)
Total QM took 20.46 s.
Submitting electronic structure for step 794.
	Gaussian terminated normally in 30.76 s. (GS_NEW)
Total QM took 30.88 s.
Submitting electronic structure for step 795.
	Gaussian terminated normally in 26.62 s. (GS_NEW)
Total QM took 26.73 s.
Submitting electronic structure for step 796.
	Gaussian terminated normally in 22.66 s. (GS_NEW)
Total QM took 22.77 s.
Submitting electronic structure for step 797.
	Gaussian terminated normally in 25.26 s. (GS_NEW)
Total QM took 25.37 s.
Submitting electronic structure for step 798.
	Gaussian terminated normally in 27.69 s. (GS_NEW)
Total QM took 27.80 s.
Submitting electronic structure for step 799.
	Gaussian terminated normally in 24.10 s. (GS_NEW)
Total QM took 24.21 s.
Submitting electronic structure for step 800.
	Gaussian terminated normally in 31.64 s. (GS_NEW)
Total QM took 31.75 s.
Submitting electronic structure for step 801.
	Gaussian terminated normally in 32.18 s. (GS_NEW)
Total QM took 32.29 s.
Submitting electronic structure for step 802.
	Gaussian terminated normally in 28.30 s. (GS_NEW)
Total QM took 28.41 s.
Submitting electronic structure for step 803.
	Gaussian terminated normally in 31.89 s. (GS_NEW)
Total QM took 32.00 s.
Submitting electronic structure for step 804.
	Gaussian terminated normally in 23.85 s. (GS_NEW)
Total QM took 23.96 s.
Submitting electronic structure for step 805.
	Gaussian terminated normally in 22.25 s. (GS_NEW)
Total QM took 22.37 s.
Submitting electronic structure for step 806.
	Gaussian terminated normally in 33.17 s. (GS_NEW)
Total QM took 33.28 s.
Submitting electronic structure for step 807.
	Gaussian terminated normally in 23.74 s. (GS_NEW)
Total QM took 23.85 s.
Submitting electronic structure for step 808.
	Gaussian terminated normally in 30.29 s. (GS_NEW)
Total QM took 30.42 s.
Submitting electronic structure for step 809.
	Gaussian terminated normally in 34.57 s. (GS_NEW)
Total QM took 34.69 s.
Submitting electronic structure for step 810.
	Gaussian terminated normally in 25.87 s. (GS_NEW)
Total QM took 25.98 s.
Submitting electronic structure for step 811.
	Gaussian terminated normally in 25.48 s. (GS_NEW)
Total QM took 25.59 s.
Submitting electronic structure for step 812.
	Gaussian terminated normally in 23.25 s. (GS_NEW)
Total QM took 23.37 s.
Submitting electronic structure for step 813.
	Gaussian terminated normally in 30.26 s. (GS_NEW)
Total QM took 30.37 s.
Submitting electronic structure for step 814.
	Gaussian terminated normally in 28.22 s. (GS_NEW)
Total QM took 28.33 s.
Submitting electronic structure for step 815.
	Gaussian terminated normally in 23.91 s. (GS_NEW)
Total QM took 24.05 s.
Submitting electronic structure for step 816.
	Gaussian terminated normally in 25.16 s. (GS_NEW)
Total QM took 25.32 s.
Submitting electronic structure for step 817.
	Gaussian terminated normally in 24.53 s. (GS_NEW)
Total QM took 25.58 s.
Submitting electronic structure for step 818.
	Gaussian terminated normally in 24.81 s. (GS_NEW)
Total QM took 24.93 s.
Submitting electronic structure for step 819.
	Gaussian terminated normally in 25.39 s. (GS_NEW)
Total QM took 25.51 s.
Submitting electronic structure for step 820.
	Gaussian terminated normally in 24.86 s. (GS_NEW)
Total QM took 25.28 s.
Submitting electronic structure for step 821.
	Gaussian terminated normally in 25.76 s. (GS_NEW)
Total QM took 25.88 s.
Submitting electronic structure for step 822.
	Gaussian terminated normally in 26.74 s. (GS_NEW)
Total QM took 26.86 s.
Submitting electronic structure for step 823.
	Gaussian terminated normally in 23.19 s. (GS_NEW)
Total QM took 23.30 s.
Submitting electronic structure for step 824.
	Gaussian terminated normally in 28.52 s. (GS_NEW)
Total QM took 28.63 s.
Submitting electronic structure for step 825.
	Gaussian terminated normally in 25.78 s. (GS_NEW)
Total QM took 25.89 s.
Submitting electronic structure for step 826.
	Gaussian terminated normally in 28.91 s. (GS_NEW)
Total QM took 29.76 s.
Submitting electronic structure for step 827.
	Gaussian terminated normally in 29.24 s. (GS_NEW)
Total QM took 30.26 s.
Submitting electronic structure for step 828.
	Gaussian terminated normally in 22.03 s. (GS_NEW)
Total QM took 22.32 s.
Submitting electronic structure for step 829.
	Gaussian terminated normally in 27.89 s. (GS_NEW)
Total QM took 28.01 s.
Submitting electronic structure for step 830.
	Gaussian terminated normally in 26.36 s. (GS_NEW)
Total QM took 26.47 s.
Submitting electronic structure for step 831.
	Gaussian terminated normally in 30.50 s. (GS_NEW)
Total QM took 30.61 s.
Submitting electronic structure for step 832.
	Gaussian terminated normally in 20.89 s. (GS_NEW)
Total QM took 21.00 s.
Submitting electronic structure for step 833.
	Gaussian terminated normally in 30.64 s. (GS_NEW)
Total QM took 30.75 s.
Submitting electronic structure for step 834.
	Gaussian terminated normally in 22.48 s. (GS_NEW)
Total QM took 22.86 s.
Submitting electronic structure for step 835.
	Gaussian terminated normally in 27.09 s. (GS_NEW)
Total QM took 28.51 s.
Submitting electronic structure for step 836.
	Gaussian terminated normally in 27.95 s. (GS_NEW)
Total QM took 28.07 s.
Submitting electronic structure for step 837.
	Gaussian terminated normally in 24.66 s. (GS_NEW)
Total QM took 24.78 s.
Submitting electronic structure for step 838.
	Gaussian terminated normally in 29.63 s. (GS_NEW)
Total QM took 30.37 s.
Submitting electronic structure for step 839.
	Gaussian terminated normally in 22.79 s. (GS_NEW)
Total QM took 22.90 s.
Submitting electronic structure for step 840.
	Gaussian terminated normally in 22.70 s. (GS_NEW)
Total QM took 22.81 s.
Submitting electronic structure for step 841.
	Gaussian terminated normally in 26.84 s. (GS_NEW)
Total QM took 26.95 s.
Submitting electronic structure for step 842.
	Gaussian terminated normally in 28.45 s. (GS_NEW)
Total QM took 28.56 s.
Submitting electronic structure for step 843.
	Gaussian terminated normally in 22.62 s. (GS_NEW)
Total QM took 22.74 s.
Submitting electronic structure for step 844.
	Gaussian terminated normally in 29.25 s. (GS_NEW)
Total QM took 29.36 s.
Submitting electronic structure for step 845.
	Gaussian terminated normally in 29.96 s. (GS_NEW)
Total QM took 30.07 s.
Submitting electronic structure for step 846.
	Gaussian terminated normally in 23.45 s. (GS_NEW)
Total QM took 23.56 s.
Submitting electronic structure for step 847.
	Gaussian terminated normally in 30.37 s. (GS_NEW)
Total QM took 30.48 s.
Submitting electronic structure for step 848.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 27.70 s.
Submitting electronic structure for step 849.
	Gaussian terminated normally in 24.82 s. (GS_NEW)
Total QM took 24.93 s.
Submitting electronic structure for step 850.
	Gaussian terminated normally in 27.82 s. (GS_NEW)
Total QM took 27.94 s.
Submitting electronic structure for step 851.
	Gaussian terminated normally in 29.69 s. (GS_NEW)
Total QM took 29.80 s.
Submitting electronic structure for step 852.
	Gaussian terminated normally in 22.93 s. (GS_NEW)
Total QM took 23.04 s.
Submitting electronic structure for step 853.
	Gaussian terminated normally in 20.28 s. (GS_NEW)
Total QM took 20.52 s.
Submitting electronic structure for step 854.
	Gaussian terminated normally in 29.20 s. (GS_NEW)
Total QM took 29.31 s.
Submitting electronic structure for step 855.
	Gaussian terminated normally in 21.03 s. (GS_NEW)
Total QM took 21.15 s.
Submitting electronic structure for step 856.
	Gaussian terminated normally in 25.19 s. (GS_NEW)
Total QM took 25.31 s.
Submitting electronic structure for step 857.
	Gaussian terminated normally in 25.89 s. (GS_NEW)
Total QM took 26.00 s.
Submitting electronic structure for step 858.
	Gaussian terminated normally in 27.68 s. (GS_NEW)
Total QM took 27.79 s.
Submitting electronic structure for step 859.
	Gaussian terminated normally in 32.48 s. (GS_NEW)
Total QM took 32.59 s.
Submitting electronic structure for step 860.
	Gaussian terminated normally in 25.93 s. (GS_NEW)
Total QM took 26.04 s.
Submitting electronic structure for step 861.
	Gaussian terminated normally in 21.92 s. (GS_NEW)
Total QM took 22.04 s.
Submitting electronic structure for step 862.
	Gaussian terminated normally in 25.23 s. (GS_NEW)
Total QM took 25.34 s.
Submitting electronic structure for step 863.
	Gaussian terminated normally in 24.49 s. (GS_NEW)
Total QM took 24.61 s.
Submitting electronic structure for step 864.
	Gaussian terminated normally in 31.95 s. (GS_NEW)
Total QM took 32.06 s.
Submitting electronic structure for step 865.
	Gaussian terminated normally in 21.15 s. (GS_NEW)
Total QM took 22.50 s.
Submitting electronic structure for step 866.
	Gaussian terminated normally in 28.84 s. (GS_NEW)
Total QM took 28.95 s.
Submitting electronic structure for step 867.
	Gaussian terminated normally in 21.36 s. (GS_NEW)
Total QM took 21.47 s.
Submitting electronic structure for step 868.
	Gaussian terminated normally in 24.89 s. (GS_NEW)
Total QM took 25.00 s.
Submitting electronic structure for step 869.
	Gaussian terminated normally in 25.04 s. (GS_NEW)
Total QM took 25.16 s.
Submitting electronic structure for step 870.
	Gaussian terminated normally in 24.57 s. (GS_NEW)
Total QM took 24.68 s.
Submitting electronic structure for step 871.
	Gaussian terminated normally in 23.17 s. (GS_NEW)
Total QM took 23.87 s.
Submitting electronic structure for step 872.
	Gaussian terminated normally in 24.23 s. (GS_NEW)
Total QM took 24.34 s.
Submitting electronic structure for step 873.
	Gaussian terminated normally in 26.10 s. (GS_NEW)
Total QM took 27.36 s.
Submitting electronic structure for step 874.
	Gaussian terminated normally in 32.17 s. (GS_NEW)
Total QM took 32.28 s.
Submitting electronic structure for step 875.
	Gaussian terminated normally in 29.02 s. (GS_NEW)
Total QM took 29.13 s.
Submitting electronic structure for step 876.
	Gaussian terminated normally in 28.51 s. (GS_NEW)
Total QM took 28.62 s.
Submitting electronic structure for step 877.
	Gaussian terminated normally in 26.20 s. (GS_NEW)
Total QM took 26.32 s.
Submitting electronic structure for step 878.
	Gaussian terminated normally in 23.70 s. (GS_NEW)
Total QM took 23.82 s.
Submitting electronic structure for step 879.
	Gaussian terminated normally in 27.11 s. (GS_NEW)
Total QM took 27.22 s.
Submitting electronic structure for step 880.
	Gaussian terminated normally in 25.25 s. (GS_NEW)
Total QM took 25.36 s.
Submitting electronic structure for step 881.
	Gaussian terminated normally in 28.27 s. (GS_NEW)
Total QM took 28.60 s.
Submitting electronic structure for step 882.
	Gaussian terminated normally in 26.61 s. (GS_NEW)
Total QM took 26.76 s.
Submitting electronic structure for step 883.
	Gaussian terminated normally in 26.97 s. (GS_NEW)
Total QM took 27.09 s.
Submitting electronic structure for step 884.
	Gaussian terminated normally in 25.25 s. (GS_NEW)
Total QM took 25.37 s.
Submitting electronic structure for step 885.
	Gaussian terminated normally in 30.99 s. (GS_NEW)
Total QM took 31.10 s.
Submitting electronic structure for step 886.
	Gaussian terminated normally in 20.05 s. (GS_NEW)
Total QM took 20.16 s.
Submitting electronic structure for step 887.
	Gaussian terminated normally in 26.54 s. (GS_NEW)
Total QM took 26.65 s.
Submitting electronic structure for step 888.
	Gaussian terminated normally in 26.21 s. (GS_NEW)
Total QM took 26.32 s.
Submitting electronic structure for step 889.
	Gaussian terminated normally in 28.51 s. (GS_NEW)
Total QM took 28.62 s.
Submitting electronic structure for step 890.
	Gaussian terminated normally in 24.46 s. (GS_NEW)
Total QM took 24.57 s.
Submitting electronic structure for step 891.
	Gaussian terminated normally in 30.18 s. (GS_NEW)
Total QM took 30.40 s.
Submitting electronic structure for step 892.
	Gaussian terminated normally in 28.53 s. (GS_NEW)
Total QM took 28.64 s.
Submitting electronic structure for step 893.
	Gaussian terminated normally in 24.76 s. (GS_NEW)
Total QM took 26.08 s.
Submitting electronic structure for step 894.
	Gaussian terminated normally in 30.00 s. (GS_NEW)
Total QM took 30.12 s.
Submitting electronic structure for step 895.
	Gaussian terminated normally in 30.01 s. (GS_NEW)
Total QM took 30.12 s.
Submitting electronic structure for step 896.
	Gaussian terminated normally in 25.12 s. (GS_NEW)
Total QM took 25.24 s.
Submitting electronic structure for step 897.
	Gaussian terminated normally in 23.72 s. (GS_NEW)
Total QM took 23.83 s.
Submitting electronic structure for step 898.
	Gaussian terminated normally in 21.62 s. (GS_NEW)
Total QM took 21.73 s.
Submitting electronic structure for step 899.
	Gaussian terminated normally in 31.05 s. (GS_NEW)
Total QM took 31.16 s.
Submitting electronic structure for step 900.
	Gaussian terminated normally in 26.91 s. (GS_NEW)
Total QM took 27.02 s.
Submitting electronic structure for step 901.
	Gaussian terminated normally in 30.75 s. (GS_NEW)
Total QM took 31.14 s.
Submitting electronic structure for step 902.
	Gaussian terminated normally in 29.11 s. (GS_NEW)
Total QM took 29.22 s.
Submitting electronic structure for step 903.
	Gaussian terminated normally in 30.80 s. (GS_NEW)
Total QM took 31.13 s.
Submitting electronic structure for step 904.
	Gaussian terminated normally in 25.72 s. (GS_NEW)
Total QM took 25.84 s.
Submitting electronic structure for step 905.
	Gaussian terminated normally in 23.69 s. (GS_NEW)
Total QM took 23.80 s.
Submitting electronic structure for step 906.
	Gaussian terminated normally in 28.15 s. (GS_NEW)
Total QM took 28.57 s.
Submitting electronic structure for step 907.
	Gaussian terminated normally in 24.53 s. (GS_NEW)
Total QM took 24.64 s.
Submitting electronic structure for step 908.
	Gaussian terminated normally in 30.00 s. (GS_NEW)
Total QM took 30.12 s.
Submitting electronic structure for step 909.
	Gaussian terminated normally in 22.35 s. (GS_NEW)
Total QM took 22.46 s.
Submitting electronic structure for step 910.
	Gaussian terminated normally in 30.48 s. (GS_NEW)
Total QM took 30.59 s.
Submitting electronic structure for step 911.
	Gaussian terminated normally in 28.71 s. (GS_NEW)
Total QM took 28.83 s.
Submitting electronic structure for step 912.
	Gaussian terminated normally in 26.75 s. (GS_NEW)
Total QM took 26.87 s.
Submitting electronic structure for step 913.
	Gaussian terminated normally in 29.40 s. (GS_NEW)
Total QM took 29.52 s.
Submitting electronic structure for step 914.
	Gaussian terminated normally in 31.48 s. (GS_NEW)
Total QM took 32.69 s.
Submitting electronic structure for step 915.
	Gaussian terminated normally in 27.35 s. (GS_NEW)
Total QM took 27.46 s.
Submitting electronic structure for step 916.
	Gaussian terminated normally in 23.69 s. (GS_NEW)
Total QM took 23.81 s.
Submitting electronic structure for step 917.
	Gaussian terminated normally in 18.42 s. (GS_NEW)
Total QM took 18.53 s.
Submitting electronic structure for step 918.
	Gaussian terminated normally in 23.99 s. (GS_NEW)
Total QM took 24.11 s.
Submitting electronic structure for step 919.
	Gaussian terminated normally in 28.08 s. (GS_NEW)
Total QM took 29.07 s.
Submitting electronic structure for step 920.
	Gaussian terminated normally in 26.63 s. (GS_NEW)
Total QM took 26.74 s.
Submitting electronic structure for step 921.
	Gaussian terminated normally in 28.48 s. (GS_NEW)
Total QM took 28.59 s.
Submitting electronic structure for step 922.
	Gaussian terminated normally in 22.23 s. (GS_NEW)
Total QM took 22.35 s.
Submitting electronic structure for step 923.
	Gaussian terminated normally in 23.93 s. (GS_NEW)
Total QM took 24.04 s.
Submitting electronic structure for step 924.
	Gaussian terminated normally in 26.14 s. (GS_NEW)
Total QM took 26.25 s.
Submitting electronic structure for step 925.
	Gaussian terminated normally in 29.43 s. (GS_NEW)
Total QM took 29.55 s.
Submitting electronic structure for step 926.
	Gaussian terminated normally in 25.06 s. (GS_NEW)
Total QM took 25.17 s.
Submitting electronic structure for step 927.
	Gaussian terminated normally in 19.93 s. (GS_NEW)
Total QM took 20.04 s.
Submitting electronic structure for step 928.
	Gaussian terminated normally in 23.57 s. (GS_NEW)
Total QM took 23.68 s.
Submitting electronic structure for step 929.
	Gaussian terminated normally in 24.62 s. (GS_NEW)
Total QM took 24.74 s.
Submitting electronic structure for step 930.
	Gaussian terminated normally in 21.76 s. (GS_NEW)
Total QM took 21.87 s.
Submitting electronic structure for step 931.
	Gaussian terminated normally in 32.27 s. (GS_NEW)
Total QM took 32.38 s.
Submitting electronic structure for step 932.
	Gaussian terminated normally in 23.49 s. (GS_NEW)
Total QM took 23.61 s.
Submitting electronic structure for step 933.
	Gaussian terminated normally in 27.88 s. (GS_NEW)
Total QM took 28.00 s.
Submitting electronic structure for step 934.
	Gaussian terminated normally in 26.65 s. (GS_NEW)
Total QM took 26.78 s.
Submitting electronic structure for step 935.
	Gaussian terminated normally in 27.04 s. (GS_NEW)
Total QM took 27.15 s.
Submitting electronic structure for step 936.
	Gaussian terminated normally in 23.48 s. (GS_NEW)
Total QM took 23.60 s.
Submitting electronic structure for step 937.
	Gaussian terminated normally in 23.34 s. (GS_NEW)
Total QM took 23.45 s.
Submitting electronic structure for step 938.
	Gaussian terminated normally in 22.81 s. (GS_NEW)
Total QM took 25.41 s.
Submitting electronic structure for step 939.
	Gaussian terminated normally in 26.76 s. (GS_NEW)
Total QM took 26.87 s.
Submitting electronic structure for step 940.
	Gaussian terminated normally in 27.92 s. (GS_NEW)
Total QM took 28.03 s.
Submitting electronic structure for step 941.
	Gaussian terminated normally in 25.41 s. (GS_NEW)
Total QM took 25.52 s.
Submitting electronic structure for step 942.
	Gaussian terminated normally in 22.47 s. (GS_NEW)
Total QM took 22.59 s.
Submitting electronic structure for step 943.
	Gaussian terminated normally in 29.80 s. (GS_NEW)
Total QM took 29.92 s.
Submitting electronic structure for step 944.
	Gaussian terminated normally in 25.61 s. (GS_NEW)
Total QM took 25.72 s.
Submitting electronic structure for step 945.
	Gaussian terminated normally in 21.53 s. (GS_NEW)
Total QM took 21.65 s.
Submitting electronic structure for step 946.
	Gaussian terminated normally in 24.12 s. (GS_NEW)
Total QM took 25.09 s.
Submitting electronic structure for step 947.
	Gaussian terminated normally in 26.70 s. (GS_NEW)
Total QM took 26.81 s.
Submitting electronic structure for step 948.
	Gaussian terminated normally in 30.46 s. (GS_NEW)
Total QM took 30.83 s.
Submitting electronic structure for step 949.
	Gaussian terminated normally in 25.35 s. (GS_NEW)
Total QM took 25.46 s.
Submitting electronic structure for step 950.
	Gaussian terminated normally in 25.87 s. (GS_NEW)
Total QM took 26.47 s.
Submitting electronic structure for step 951.
	Gaussian terminated normally in 30.87 s. (GS_NEW)
Total QM took 30.98 s.
Submitting electronic structure for step 952.
	Gaussian terminated normally in 25.49 s. (GS_NEW)
Total QM took 25.60 s.
Submitting electronic structure for step 953.
	Gaussian terminated normally in 23.95 s. (GS_NEW)
Total QM took 24.06 s.
Submitting electronic structure for step 954.
	Gaussian terminated normally in 30.91 s. (GS_NEW)
Total QM took 31.44 s.
Submitting electronic structure for step 955.
	Gaussian terminated normally in 29.79 s. (GS_NEW)
Total QM took 29.90 s.
Submitting electronic structure for step 956.
	Gaussian terminated normally in 24.78 s. (GS_NEW)
Total QM took 24.89 s.
Submitting electronic structure for step 957.
	Gaussian terminated normally in 29.55 s. (GS_NEW)
Total QM took 29.94 s.
Submitting electronic structure for step 958.
	Gaussian terminated normally in 20.87 s. (GS_NEW)
Total QM took 20.98 s.
Submitting electronic structure for step 959.
	Gaussian terminated normally in 20.79 s. (GS_NEW)
Total QM took 20.91 s.
Submitting electronic structure for step 960.
	Gaussian terminated normally in 26.46 s. (GS_NEW)
Total QM took 26.57 s.
Submitting electronic structure for step 961.
	Gaussian terminated normally in 31.43 s. (GS_NEW)
Total QM took 31.56 s.
Submitting electronic structure for step 962.
	Gaussian terminated normally in 26.13 s. (GS_NEW)
Total QM took 26.25 s.
Submitting electronic structure for step 963.
	Gaussian terminated normally in 178.77 s. (GS_NEW)
Total QM took 178.89 s.
Submitting electronic structure for step 964.
	Gaussian terminated normally in 22.36 s. (GS_NEW)
Total QM took 22.47 s.
Submitting electronic structure for step 965.
	Gaussian terminated normally in 24.85 s. (GS_NEW)
Total QM took 24.97 s.
Submitting electronic structure for step 966.
	Gaussian terminated normally in 26.63 s. (GS_NEW)
Total QM took 26.74 s.
Submitting electronic structure for step 967.
	Gaussian terminated normally in 28.00 s. (GS_NEW)
Total QM took 28.11 s.
Submitting electronic structure for step 968.
	Gaussian terminated normally in 31.49 s. (GS_NEW)
Total QM took 33.18 s.
Submitting electronic structure for step 969.
	Gaussian terminated normally in 98.66 s. (GS_NEW)
Total QM took 98.77 s.
Submitting electronic structure for step 970.
	Gaussian terminated normally in 19.86 s. (GS_NEW)
Total QM took 19.97 s.
Submitting electronic structure for step 971.
	Gaussian terminated normally in 28.86 s. (GS_NEW)
Total QM took 28.97 s.
Submitting electronic structure for step 972.
	Gaussian terminated normally in 34.11 s. (GS_NEW)
Total QM took 37.10 s.
Submitting electronic structure for step 973.
	Gaussian terminated normally in 23.08 s. (GS_NEW)
Total QM took 23.19 s.
Submitting electronic structure for step 974.
	Gaussian terminated normally in 20.36 s. (GS_NEW)
Total QM took 20.47 s.
Submitting electronic structure for step 975.
	Gaussian terminated normally in 25.26 s. (GS_NEW)
Total QM took 25.37 s.
Submitting electronic structure for step 976.
	Gaussian terminated normally in 29.04 s. (GS_NEW)
Total QM took 29.16 s.
Submitting electronic structure for step 977.
	Gaussian terminated normally in 20.77 s. (GS_NEW)
Total QM took 20.99 s.
Submitting electronic structure for step 978.
	Gaussian terminated normally in 24.66 s. (GS_NEW)
Total QM took 26.28 s.
Submitting electronic structure for step 979.
	Gaussian terminated normally in 17.83 s. (GS_NEW)
Total QM took 17.94 s.
Submitting electronic structure for step 980.
	Gaussian terminated normally in 190.54 s. (GS_NEW)
Total QM took 191.59 s.
Submitting electronic structure for step 981.
	Gaussian terminated normally in 16.17 s. (GS_NEW)
Total QM took 16.58 s.
Submitting electronic structure for step 982.
	Gaussian terminated normally in 31.79 s. (GS_NEW)
Total QM took 31.90 s.
Submitting electronic structure for step 983.
	Gaussian terminated normally in 180.53 s. (GS_NEW)
Total QM took 180.65 s.
Submitting electronic structure for step 984.
	Gaussian terminated normally in 27.63 s. (GS_NEW)
Total QM took 27.75 s.
Submitting electronic structure for step 985.
	Gaussian terminated normally in 26.80 s. (GS_NEW)
Total QM took 26.92 s.
Submitting electronic structure for step 986.
	Gaussian terminated normally in 28.89 s. (GS_NEW)
Total QM took 29.14 s.
Submitting electronic structure for step 987.
	Gaussian terminated normally in 27.29 s. (GS_NEW)
Total QM took 27.40 s.
Submitting electronic structure for step 988.
	Gaussian terminated normally in 29.95 s. (GS_NEW)
Total QM took 30.50 s.
Submitting electronic structure for step 989.
	Gaussian terminated normally in 101.75 s. (GS_NEW)
Total QM took 101.86 s.
Submitting electronic structure for step 990.
	Gaussian terminated normally in 27.90 s. (GS_NEW)
Total QM took 28.01 s.
Submitting electronic structure for step 991.
	Gaussian terminated normally in 14.89 s. (GS_NEW)
Total QM took 15.00 s.
Submitting electronic structure for step 992.
	Gaussian terminated normally in 25.97 s. (GS_NEW)
Total QM took 26.08 s.
Submitting electronic structure for step 993.
	Gaussian terminated normally in 26.51 s. (GS_NEW)
Total QM took 26.63 s.
Submitting electronic structure for step 994.
	Gaussian terminated normally in 21.84 s. (GS_NEW)
Total QM took 21.95 s.
Submitting electronic structure for step 995.
	Gaussian terminated normally in 21.29 s. (GS_NEW)
Total QM took 21.40 s.
Submitting electronic structure for step 996.
	Gaussian terminated normally in 24.54 s. (GS_NEW)
Total QM took 24.72 s.
Submitting electronic structure for step 997.
	Gaussian terminated normally in 25.76 s. (GS_NEW)
Total QM took 25.87 s.
Submitting electronic structure for step 998.
	Gaussian terminated normally in 21.81 s. (GS_NEW)
Total QM took 21.93 s.
Submitting electronic structure for step 999.
	Gaussian terminated normally in 24.62 s. (GS_NEW)
Total QM took 24.73 s.
Submitting electronic structure for step 1000.
	Gaussian terminated normally in 21.18 s. (GS_NEW)
Total QM took 21.29 s.
